-- GENERATED by `make gen` from dbt/poker_dwh (the macros and models named below) -- edit the dbt models, not this file.
-- The worker's derivation of one batch into marts.decisions (plan E.1b, ADR-047):
-- models/marts/decisions.sql rendered with the batch predicate in place of dbt's partition gate,
-- `int_board_by_street` inlined, and `built_by = 'hot'` so that dbt's gate knows the
-- partition is not its own work yet. Three parameters: tenant, stamp, partitions.
INSERT INTO marts.decisions
SELECT * FROM (
-- ★ THE DECISION FACT: one row per decision point, with the state before it (ADR-020).
--
-- Any situation is a predicate over one of these rows, and any situation stat is
-- countIf(situation AND action) / countIf(situation). That is what replaces the 156-column
-- flag table: a new stat is a registry entry, a new situation is a filter, and neither touches
-- this model. The columns are the contract in stats/registry/dimensions.yaml; the SELECT is
-- macros/decision_state.sql (see there for why it is a macro).
--
-- Sort key: `user_id` leads, then `dataset` so a hero-only query never touches a pool granule,
-- then `player_key_norm` (every opponent report filters on it), `street` (most stats fix one),
-- the day, and the hand and action for locality. `player_key_norm` rather than `player_key`
-- because ClickHouse refuses a Nullable sort key; anonymized seats get '' and aggregate as
-- population, `player_key` stays NULL for the opponent-stat gate.
--
-- Same daily partitions and dirty-partition gate as the rest of the chain (ADR-019).




select
    user_id, dataset, hand_uid, played_at_utc, played_date,
    seat, player_key, player_key_norm, is_hero, is_anonymized,
    action_index, decision_idx, street,
    site, stake_level, game_type, table_format, big_blind, players_dealt_in, position,
    n_raises_preflop, n_limpers, n_callers_before, n_cold_callers,
    am_preflop_opener, am_preflop_aggressor, opener_position, last_raiser_position, pot_type,
    n_bets_street, n_raises_street, facing, facing_is_cbet, facing_size_pct,
    to_call_bb, pot_before_bb, invested_bb,
    players_live, players_acted_before, is_first_to_act, is_last_to_act, is_ip,
    am_prev_street_aggressor, prev_street_my_action, prev_street_faced,
    preflop_line, street_line, line_so_far,
    eff_stack_bb, spr,
    flop_suitedness, flop_pairing, flop_high_card, flop_connectedness, flop_span,
    turn_rank, turn_completes_flush, turn_pairs_board,
    river_rank, river_completes_flush, river_pairs_board,
    board_paired, board_flush_possible, board_straight_possible,
    hand_class, hand_shape, hole_cards, made_hand,
    action, is_allin, amount_bb, size_pct, raise_to_bb,
    saw_next_street, went_to_showdown, won_hand, net_won_bb, ev_won_bb,
    parser_version, src_parsed_at, built_by
from (
    select
        -- ---- identity ----------------------------------------------------------------
        hb.user_id                                                   as user_id,
        hb.dataset                                                   as dataset,
        hb.hand_uid                                                  as hand_uid,
        hb.played_at_utc                                             as played_at_utc,
        hb.played_date                                               as played_date,
        hb.a_seat[k]                                                 as seat,
        hb.a_st[k]                                                   as st,
        hb.a_tok[k]                                                  as tok,
        indexOf(hb.s_seat, seat)                                     as si,
        hb.s_player_key[si]                                          as player_key,
        hb.s_player_key_norm[si]                                     as player_key_norm,
        hb.s_is_hero[si]                                             as is_hero,
        hb.s_is_anonymized[si]                                       as is_anonymized,
        hb.a_idx[k]                                                  as action_index,

        -- ---- everything before this decision -----------------------------------------
        arraySlice(hb.a_idx, 1, k - 1)                               as p_idx,
        arraySlice(hb.a_seat, 1, k - 1)                              as p_seat,
        arraySlice(hb.a_st, 1, k - 1)                                as p_st,
        arraySlice(hb.a_tok, 1, k - 1)                               as p_tok,
        arraySlice(hb.a_amt, 1, k - 1)                               as p_amt,
        arraySlice(hb.a_pot, 1, k - 1)                               as p_pot,
        arraySlice(hb.a_allin, 1, k - 1)                             as p_allin,

        toUInt8(arrayCount((s, t) -> s = seat and t != 'p', p_seat, p_tok)) as decision_idx,
        cast(multiIf(st = 0, 'preflop', st = 1, 'flop', st = 2, 'turn', 'river')
             as Enum8('preflop' = 0, 'flop' = 1, 'turn' = 2, 'river' = 3)) as street,

        -- ---- table dimensions --------------------------------------------------------
        hb.site                                                      as site,
        hb.stake_level                                               as stake_level,
        hb.game_type                                                 as game_type,
        hb.table_format                                              as table_format,
        hb.big_blind                                                 as big_blind,
        hb.players_dealt_in                                          as players_dealt_in,
        hb.s_position[si]::LowCardinality(String)                    as position,
        hb.pot_type                                                  as pot_type,

        -- ---- preflop state as of this decision ---------------------------------------
        toUInt8(arrayCount((t, s) -> s = 0 and t = 'r', p_tok, p_st))  as n_raises_preflop,
        toUInt8(arrayCount((t, s) -> s = 0 and t = 'l', p_tok, p_st))  as n_limpers,
        toUInt8(arrayCount((t, s) -> s = 0 and t = 'c', p_tok, p_st))  as n_cold_callers,
        toUInt8(arrayCount((t, s) -> s = st and t in ('l', 'c'), p_tok, p_st)) as n_callers_before,
        -- p_seat[0] is 0 (out of range reads the default), so "no raise yet" is seat 0.
        p_seat[arrayFirstIndex((t, s) -> s = 0 and t = 'r', p_tok, p_st)] as opener_seat,
        p_seat[arrayLastIndex((t, s) -> s = 0 and t = 'r', p_tok, p_st)]  as aggressor_seat,
        toUInt8(opener_seat = seat)                                  as am_preflop_opener,
        toUInt8(aggressor_seat = seat)                               as am_preflop_aggressor,
        hb.s_position[indexOf(hb.s_seat, opener_seat)]::LowCardinality(String) as opener_position,

        -- ---- this street as of this decision -----------------------------------------
        toUInt8(arrayCount((t, s) -> s = st and t in ('b', 'r'), p_tok, p_st)) as n_bets_street,
        toUInt8(arrayCount((t, s) -> s = st and t = 'r', p_tok, p_st))        as n_raises_street,
        arrayFirstIndex((t, s) -> s = st and t in ('b', 'r'), p_tok, p_st)    as first_aggr_k,
        arrayLastIndex((t, s) -> s = st and t in ('b', 'r'), p_tok, p_st)     as last_aggr_k,
        hb.s_position[indexOf(hb.s_seat, p_seat[last_aggr_k])]::LowCardinality(String)
                                                                     as last_raiser_position,
        multiIf(
            st = 0 and n_raises_preflop = 0 and n_limpers = 0, 'none',
            st = 0 and n_raises_preflop = 0, 'limp',
            st = 0 and n_raises_preflop = 1, 'raise',
            st = 0 and n_raises_preflop = 2, '3bet',
            st = 0 and n_raises_preflop = 3, '4bet',
            st = 0, '5bet_plus',
            n_bets_street = 0, 'none',
            n_bets_street = 1, 'bet',
            n_bets_street = 2, 'raise',
            '3bet'
        )::LowCardinality(String)                                    as facing,
        toUInt8(st > 0 and n_bets_street = 1 and aggressor_seat > 0
                and p_seat[first_aggr_k] = aggressor_seat)           as facing_is_cbet,
        toFloat32(coalesce(p_amt[last_aggr_k] / nullIf(p_pot[last_aggr_k], 0), 0)) as facing_size_pct,
        hb.a_call[k]                                                 as to_call_bb,
        hb.a_pot[k]                                                  as pot_before_bb,
        -- The seat's OWN chips already in the middle, blinds and antes included. `pot_before_bb`
        -- is everybody's; this is the part that is already sunk for this seat, which is what
        -- turns the hand-level `net_won_bb` into "chips won from this point"
        -- (`net_won_bb + invested_bb`) for empirical EQR -- spec §10.4, plan F.10.
        -- Safe to sum: `acts` in hand_arrays.sql keeps only posts and the five real actions, so
        -- an uncalled return is never in these arrays and there is nothing to subtract.
        toFloat32(arraySum(arrayFilter((amt, s) -> s = seat, p_amt, p_seat))) as invested_bb,

        -- ---- who is still in, who has acted ------------------------------------------
        arrayDistinct(arrayFilter((s, t) -> t = 'f', p_seat, p_tok))  as folded_seats,
        arrayDistinct(arrayFilter((s, a) -> a = 1, p_seat, p_allin))  as allin_seats,
        toUInt8(hb.players_dealt_in - length(folded_seats))          as players_live,
        toUInt8(length(arrayDistinct(arrayFilter((s, s2, t) -> s2 = st and t != 'p',
                                                 p_seat, p_st, p_tok)))) as players_acted_before,
        toUInt8(players_acted_before = 0)                            as is_first_to_act,
        -- Every other live player is "settled" for this round when it has acted on this street
        -- without folding, or is all-in and cannot act again.
        arrayDistinct(arrayConcat(
            arrayFilter((s, s2, t) -> s2 = st and t != 'p' and s != seat
                                      and not has(folded_seats, s), p_seat, p_st, p_tok),
            allin_seats))                                            as settled_seats,
        toUInt8(length(settled_seats) + 1 >= players_live)           as is_last_to_act,
        -- Acts last among the players who act on this street (first-occurrence order).
        toUInt8(arrayElement(arrayDistinct(arrayFilter((s, s2, t) -> s2 = st and t != 'p',
                                                       hb.a_seat, hb.a_st, hb.a_tok)), -1) = seat) as is_ip,

        -- ---- the previous street (complete, so the full arrays are used) --------------
        arrayLastIndex((s2, t) -> s2 = st - 1 and t in ('b', 'r'), hb.a_st, hb.a_tok) as prev_aggr_k,
        toUInt8(prev_aggr_k > 0 and hb.a_seat[prev_aggr_k] = seat)   as am_prev_street_aggressor,
        arrayStringConcat(arrayFilter((t, s, s2) -> s = seat and s2 = st - 1 and t != 'p',
                                      hb.a_tok, hb.a_seat, hb.a_st), '-') as prev_street_my_action,
        arrayLastIndex((s, s2, t) -> s = seat and s2 = st - 1 and t != 'p',
                       hb.a_seat, hb.a_st, hb.a_tok)                 as my_prev_k,
        hb.a_idx[my_prev_k]                                          as my_prev_idx,
        toUInt8(arrayCount((i, s2, t) -> s2 = st - 1 and t in ('b', 'r') and i < my_prev_idx,
                           hb.a_idx, hb.a_st, hb.a_tok))             as prev_bets,
        toUInt8(arrayCount((i, s2, t) -> s2 = 0 and t = 'l' and i < my_prev_idx,
                           hb.a_idx, hb.a_st, hb.a_tok))             as prev_limps,
        multiIf(
            my_prev_k = 0, 'none',
            st = 1 and prev_bets = 0 and prev_limps = 0, 'none',
            st = 1 and prev_bets = 0, 'limp',
            st = 1 and prev_bets = 1, 'raise',
            st = 1 and prev_bets = 2, '3bet',
            st = 1 and prev_bets = 3, '4bet',
            st = 1, '5bet_plus',
            prev_bets = 0, 'none',
            prev_bets = 1, 'bet',
            prev_bets = 2, 'raise',
            '3bet'
        )::LowCardinality(String)                                    as prev_street_faced,

        -- ---- action lines (own actions; tokens in dimensions.yaml) --------------------
        arrayStringConcat(arrayFilter((t, s, s2) -> s = seat and s2 = 0 and t != 'p',
                                      p_tok, p_seat, p_st), '-')     as preflop_line,
        arrayStringConcat(arrayFilter((t, s, s2) -> s = seat and s2 = st and t != 'p',
                                      p_tok, p_seat, p_st), '-')     as street_line,
        arrayStringConcat(arrayMap(
            x -> arrayStringConcat(arrayFilter((t, s, s2) -> s = seat and s2 = x and t != 'p',
                                               p_tok, p_seat, p_st), '-'),
            range(st + 1)), '/')                                     as line_so_far,

        -- ---- depth -------------------------------------------------------------------
        hb.s_stack_bb[si] - arraySum(arrayFilter((a, s) -> s = seat, p_amt, p_seat)) as my_behind,
        arrayMax(arrayMap(
            j -> hb.s_stack_bb[j] - arraySum(arrayFilter((a, s) -> s = hb.s_seat[j], p_amt, p_seat)),
            arrayFilter(j -> hb.s_seat[j] != seat and not has(folded_seats, hb.s_seat[j]),
                        arrayEnumerate(hb.s_seat))))                 as opp_behind,
        toFloat32(greatest(least(my_behind, opp_behind), 0))          as eff_stack_bb,
        toFloat32(if(pot_before_bb > 0, eff_stack_bb / pot_before_bb, 0)) as spr,

        -- ---- the board at this street ------------------------------------------------
        if(st >= 1, hb.b_flop_suitedness, '')::LowCardinality(String)    as flop_suitedness,
        if(st >= 1, hb.b_flop_pairing, '')::LowCardinality(String)       as flop_pairing,
        if(st >= 1, hb.b_flop_high_card, '')::LowCardinality(String)     as flop_high_card,
        if(st >= 1, hb.b_flop_connectedness, '')::LowCardinality(String) as flop_connectedness,
        if(st >= 1, hb.b_flop_span, 0)::UInt8                            as flop_span,
        if(st >= 2, hb.b_turn_rank, '')::LowCardinality(String)          as turn_rank,
        if(st >= 2, hb.b_turn_completes_flush, 0)::UInt8                 as turn_completes_flush,
        if(st >= 2, hb.b_turn_pairs_board, 0)::UInt8                     as turn_pairs_board,
        if(st >= 3, hb.b_river_rank, '')::LowCardinality(String)         as river_rank,
        if(st >= 3, hb.b_river_completes_flush, 0)::UInt8                as river_completes_flush,
        if(st >= 3, hb.b_river_pairs_board, 0)::UInt8                    as river_pairs_board,
        multiIf(st = 1, hb.b_paired_flop, st = 2, hb.b_paired_turn, st = 3, hb.b_paired_river, 0)::UInt8
                                                                     as board_paired,
        multiIf(st = 1, hb.b_flush_flop, st = 2, hb.b_flush_turn, st = 3, hb.b_flush_river, 0)::UInt8
                                                                     as board_flush_possible,
        multiIf(st = 1, hb.b_straight_flop, st = 2, hb.b_straight_turn, st = 3, hb.b_straight_river, 0)::UInt8
                                                                     as board_straight_possible,

        -- ---- holding -----------------------------------------------------------------
        hb.s_hand_class[si]::LowCardinality(String)                  as hand_class,
        hb.s_hand_shape[si]::LowCardinality(String)                  as hand_shape,
        hb.s_hole_cards[si]                                          as hole_cards,
        -- The class for THIS street, which is why parse time stores one per street. Preflop
        -- there is no board and so no made hand: `hand_class` already carries the 169-class
        -- vocabulary there, and '' keeps "no board yet" distinct from "no pair".
        multiIf(st = 1, hb.s_made_hand_flop[si],
                st = 2, hb.s_made_hand_turn[si],
                st = 3, hb.s_made_hand_river[si], '')::LowCardinality(String) as made_hand,

        -- ---- the decision ------------------------------------------------------------
        cast(multiIf(tok = 'f', 'fold', tok = 'x', 'check', tok in ('l', 'c'), 'call',
                     tok = 'b', 'bet', 'raise')
             as Enum8('fold' = 0, 'check' = 1, 'call' = 2, 'bet' = 3, 'raise' = 4)) as action,
        hb.a_allin[k]                                                as is_allin,
        hb.a_amt[k]                                                  as amount_bb,
        toFloat32(if(tok in ('b', 'r'), coalesce(hb.a_amt[k] / nullIf(pot_before_bb, 0), 0), 0)) as size_pct,
        toFloat32(if(tok = 'r', hb.a_to[k], 0))                      as raise_to_bb,

        -- ---- the outcome (hand level, repeated) --------------------------------------
        multiIf(st = 0, hb.s_saw_flop[si], st = 1, hb.s_saw_turn[si],
                st = 2, hb.s_saw_river[si], hb.s_went_to_showdown[si]) as saw_next_street,
        hb.s_went_to_showdown[si]                                    as went_to_showdown,
        hb.s_won_hand[si]                                            as won_hand,
        hb.s_net_won_bb[si]                                          as net_won_bb,
        hb.s_ev_won_bb[si]                                           as ev_won_bb,
        hb.parser_version                                            as parser_version,
        hb.src_parsed_at                                             as src_parsed_at,
        -- Last, always: the real tables gained it by ALTER ... ADD COLUMN AFTER src_parsed_at,
        -- and REPLACE PARTITION needs the temp table's column order to match (ADR-047).
        'hot'::LowCardinality(String)                                             as built_by
    from (
        select
            h.*,
            b.flop_suitedness        as b_flop_suitedness,
            b.flop_pairing           as b_flop_pairing,
            b.flop_high_card         as b_flop_high_card,
            b.flop_connectedness     as b_flop_connectedness,
            b.flop_span              as b_flop_span,
            b.turn_rank              as b_turn_rank,
            b.turn_completes_flush   as b_turn_completes_flush,
            b.turn_pairs_board       as b_turn_pairs_board,
            b.river_rank             as b_river_rank,
            b.river_completes_flush  as b_river_completes_flush,
            b.river_pairs_board      as b_river_pairs_board,
            b.paired_flop            as b_paired_flop,
            b.paired_turn            as b_paired_turn,
            b.paired_river           as b_paired_river,
            b.flush_flop             as b_flush_flop,
            b.flush_turn             as b_flush_turn,
            b.flush_river            as b_flush_river,
            b.straight_flop          as b_straight_flop,
            b.straight_turn          as b_straight_turn,
            b.straight_river         as b_straight_river
        from (with acts as (

    select
        user_id,
        hand_uid,
        action_index,
        seat,
        multiIf(street = 'preflop', 0, street = 'flop', 1, street = 'turn', 2, 3)::UInt8 as st,
        action_type,
        amount,
        amount_to,
        pot_before,
        to_call,
        is_allin,
        is_voluntary
    from staging.stg_actions
    where action_type in ('post_sb', 'post_bb', 'post_ante', 'post_straddle', 'post_dead',
                          'fold', 'check', 'call', 'bet', 'raise')
      and toYYYYMMDD(played_at_utc) in {partitions:Array(UInt32)} and user_id = {tenant:UInt32} and src_parsed_at = {stamp:DateTime64(3, 'UTC')}

),

hand_actions as (

    select
        user_id,
        hand_uid,
        arraySort(t -> t.1, groupArray((action_index, seat, st, action_type, amount, amount_to,
                                        pot_before, to_call, is_allin, is_voluntary))) as acts,
        -- Sentinel, not 0: with no raise every preflop call must count as a limp.
        if(countIf(st = 0 and action_type = 'raise') = 0, toUInt16(65535),
           minIf(action_index, st = 0 and action_type = 'raise'))            as first_raise_idx,
        toUInt8(countIf(st = 0 and action_type = 'raise'))                   as n_preflop_raises,
        argMinIf(seat, action_index, st = 0 and action_type = 'raise')       as opener_seat,
        argMaxIf(seat, action_index, st = 0 and action_type = 'raise')       as aggressor_seat,
        argMinIf(pot_before, action_index, st = 1)                           as pot_at_flop
    from acts
    group by user_id, hand_uid

),

seats_raw as (

    select
        user_id,
        hand_uid,
        seat,
        toString(position)                                       as position,
        player_key,
        coalesce(player_key, '')                                 as player_key_norm,
        is_hero,
        is_anonymized,
        toFloat32(starting_stack_bb)                             as stack_bb,
        hole_cards,
        net_won_bb,
        coalesce(ev_won_bb, net_won_bb)                          as ev_won_bb,
        saw_flop,
        saw_turn,
        saw_river,
        went_to_showdown,
        won_hand,
        total_invested,
        -- Written at parse time by core/classify.py; '' where the cards or the board were not
        -- known. SQL cannot rank a poker hand, which is why these are columns and not an
        -- expression here (plan E.5, ADR-018).
        made_hand_flop,
        made_hand_turn,
        made_hand_river,
        -- 'AKs' / 'T9o' / 'QQ' -- the 169-combo vocabulary. Hold'em-shaped hands only.
        splitByChar(' ', hole_cards)                             as cards,
        if(length(cards) = 2, position('23456789TJQKA', substring(cards[1], 1, 1)), 0) as r1,
        if(length(cards) = 2, position('23456789TJQKA', substring(cards[2], 1, 1)), 0) as r2,
        length(cards) = 2 and substring(cards[1], 2, 1) = substring(cards[2], 2, 1) as suited,
        multiIf(
            r1 = 0 or r2 = 0, '',
            r1 = r2, concat(substring('23456789TJQKA', r1, 1), substring('23456789TJQKA', r1, 1)),
            concat(substring('23456789TJQKA', greatest(r1, r2), 1),
                   substring('23456789TJQKA', least(r1, r2), 1),
                   if(suited, 's', 'o'))
        )                                                        as hand_class,
        multiIf(r1 = 0 or r2 = 0, '', r1 = r2, 'pair', suited, 'suited', 'offsuit') as hand_shape
    from staging.stg_hand_players
    where toYYYYMMDD(played_at_utc) in {partitions:Array(UInt32)} and user_id = {tenant:UInt32} and src_parsed_at = {stamp:DateTime64(3, 'UTC')}

),

seats as (

    select
        user_id,
        hand_uid,
        arraySort(t -> t.1, groupArray((seat, position, player_key, player_key_norm, is_hero,
                                        is_anonymized, stack_bb, hole_cards, hand_class,
                                        hand_shape, net_won_bb, ev_won_bb, saw_flop, saw_turn,
                                        saw_river, went_to_showdown, won_hand,
                                        total_invested, made_hand_flop, made_hand_turn,
                                        made_hand_river)))                 as seats,
        sum(total_invested)                                                as invested_total
    from seats_raw
    group by user_id, hand_uid

)

select
    h.user_id                                                    as user_id,
    h.dataset                                                    as dataset,
    toFixedString(unhex(h.hand_uid), 16)                         as hand_uid,
    h.played_at_utc                                              as played_at_utc,
    h.played_date                                                as played_date,
    h.src_parsed_at                                              as src_parsed_at,
    h.parser_version                                             as parser_version,
    h.site                                                       as site,
    h.stake_level                                                as stake_level,
    h.game_type                                                  as game_type,
    h.table_format                                               as table_format,
    h.big_blind                                                  as big_blind,
    h.players_dealt_in                                           as players_dealt_in,

    -- ---- the action stream ----------------------------------------------------------
    arrayMap(t -> t.1, a.acts)                                   as a_idx,
    arrayMap(t -> t.2, a.acts)                                   as a_seat,
    arrayMap(t -> t.3, a.acts)                                   as a_st,
    arrayMap(t -> multiIf(
        t.4 = 'fold', 'f',
        t.4 = 'check', 'x',
        t.4 = 'call' and t.3 = 0 and t.1 < a.first_raise_idx, 'l',
        t.4 = 'call', 'c',
        t.4 = 'bet', 'b',
        t.4 = 'raise', 'r',
        'p'), a.acts)                                            as a_tok,
    arrayMap(t -> toFloat32(toFloat64(t.5) / toFloat64(h.big_blind)), a.acts) as a_amt,
    arrayMap(t -> toFloat32(toFloat64(t.6) / toFloat64(h.big_blind)), a.acts) as a_to,
    arrayMap(t -> toFloat32(toFloat64(t.7) / toFloat64(h.big_blind)), a.acts) as a_pot,
    arrayMap(t -> toFloat32(toFloat64(t.8) / toFloat64(h.big_blind)), a.acts) as a_call,
    arrayMap(t -> t.9, a.acts)                                   as a_allin,
    arrayMap(t -> t.10, a.acts)                                  as a_vol,

    -- ---- hand-level preflop facts ---------------------------------------------------
    a.first_raise_idx                                            as first_raise_idx,
    a.n_preflop_raises                                           as n_preflop_raises,
    a.opener_seat                                                as opener_seat,
    a.aggressor_seat                                             as aggressor_seat,
    multiIf(
        a.n_preflop_raises = 0, 'limped',
        a.n_preflop_raises = 1, 'srp',
        a.n_preflop_raises = 2, '3bet',
        a.n_preflop_raises = 3, '4bet',
        '5bet_plus'
    )::LowCardinality(String)                                    as pot_type,
    toFloat32(toFloat64(a.pot_at_flop) / toFloat64(h.big_blind)) as pot_at_flop_bb,
    -- The seat whose FIRST flop action comes last acts last, i.e. is in position (v1's
    -- definition, kept for parity). arrayDistinct keeps first-occurrence order.
    arrayElement(arrayDistinct(arrayFilter((s, st, t) -> st = 1 and t != 'p',
                                           a_seat, a_st, a_tok)), -1) as flop_last_seat,

    -- ---- the seats ------------------------------------------------------------------
    arrayMap(t -> t.1, s.seats)                                  as s_seat,
    arrayMap(t -> t.2, s.seats)                                  as s_position,
    arrayMap(t -> t.3, s.seats)                                  as s_player_key,
    arrayMap(t -> t.4, s.seats)                                  as s_player_key_norm,
    arrayMap(t -> t.5, s.seats)                                  as s_is_hero,
    arrayMap(t -> t.6, s.seats)                                  as s_is_anonymized,
    arrayMap(t -> t.7, s.seats)                                  as s_stack_bb,
    arrayMap(t -> t.8, s.seats)                                  as s_hole_cards,
    arrayMap(t -> t.9, s.seats)                                  as s_hand_class,
    arrayMap(t -> t.10, s.seats)                                 as s_hand_shape,
    arrayMap(t -> t.11, s.seats)                                 as s_net_won_bb,
    arrayMap(t -> t.12, s.seats)                                 as s_ev_won_bb,
    arrayMap(t -> t.13, s.seats)                                 as s_saw_flop,
    arrayMap(t -> t.14, s.seats)                                 as s_saw_turn,
    arrayMap(t -> t.15, s.seats)                                 as s_saw_river,
    arrayMap(t -> t.16, s.seats)                                 as s_went_to_showdown,
    arrayMap(t -> t.17, s.seats)                                 as s_won_hand,
    arrayMap(t -> t.19, s.seats)                                 as s_made_hand_flop,
    arrayMap(t -> t.20, s.seats)                                 as s_made_hand_turn,
    arrayMap(t -> t.21, s.seats)                                 as s_made_hand_river,
    -- Rake attributed by contribution (the "weighted contributed" convention).
    arrayMap(t -> if(s.invested_total > 0,
                     toFloat32(toFloat64(h.rake) * toFloat64(t.18)
                               / toFloat64(s.invested_total) / toFloat64(h.big_blind)),
                     toFloat32(0)), s.seats)                     as s_rake_paid_bb,
    arrayMap(x -> toUInt8(arrayExists((s2, st, v) -> s2 = x and st = 0 and v = 1,
                                      a_seat, a_st, a_vol)), s_seat)  as s_did_vpip,
    arrayMap(x -> toUInt8(arrayExists((s2, st, t) -> s2 = x and st = 0 and t = 'r',
                                      a_seat, a_st, a_tok)), s_seat)  as s_did_pfr,
    toUInt8(arraySum(s_saw_flop))                                as players_to_flop
from staging.stg_hands as h
inner join hand_actions as a
    on a.user_id = h.user_id and a.hand_uid = h.hand_uid
inner join seats as s
    on s.user_id = h.user_id and s.hand_uid = h.hand_uid
where toYYYYMMDD(h.played_at_utc) in {partitions:Array(UInt32)} and h.user_id = {tenant:UInt32} and h.src_parsed_at = {stamp:DateTime64(3, 'UTC')}
) as h
        left join (
-- Board texture per hand, AT EACH STREET: what the board looked like when the flop, turn and
-- river decisions were made. A decision on the turn must see the turn card and not the river,
-- so every feature exists three times and marts/decisions.sql picks the one for its street.
--
-- Hands that never saw a flop have no row; the LEFT JOIN in the consumers zero-pads to '' / 0,
-- which is what the registry declares for "before the flop" (stats/registry/dimensions.yaml).
--
-- Ranks are 1..13 for 2..A via position() into one rank string, the same encoding as
-- macros/hand_arrays.sql uses for hole cards.





with flop as (

    select
        user_id,
        toFixedString(unhex(hand_uid), 16)                        as hand_uid,
        played_at_utc,
        src_parsed_at,
        [board_flop_1, board_flop_2, board_flop_3]                as f,
        board_turn                                                as c4,
        board_river                                               as c5
    from staging.stg_hands
    where board_flop_1 != '' and toYYYYMMDD(played_at_utc) in {partitions:Array(UInt32)} and user_id = {tenant:UInt32} and src_parsed_at = {stamp:DateTime64(3, 'UTC')}

),

parts as (

    select
        user_id,
        hand_uid,
        played_at_utc,
        src_parsed_at,
        arrayMap(c -> position('23456789TJQKA', substring(c, 1, 1)), f)   as fr,
        arrayMap(c -> substring(c, 2, 1), f)                             as fs,
        arrayReverseSort(fr)                                             as fr_desc,
        c4 != ''                                                         as has_turn,
        c5 != ''                                                         as has_river,
        position('23456789TJQKA', substring(c4, 1, 1))                     as r4,
        substring(c4, 2, 1)                                              as s4,
        position('23456789TJQKA', substring(c5, 1, 1))                     as r5,
        substring(c5, 2, 1)                                              as s5,
        if(has_turn, arrayConcat(fr, [r4]), fr)                          as tr,
        if(has_turn, arrayConcat(fs, [s4]), fs)                          as ts,
        if(has_river, arrayConcat(tr, [r5]), tr)                         as rr,
        if(has_river, arrayConcat(ts, [s5]), ts)                         as rs
    from flop

)

select
    user_id                                                              as user_id,
    hand_uid                                                             as hand_uid,
    played_at_utc                                                        as played_at_utc,
    src_parsed_at                                                        as src_parsed_at,

    -- ---- the flop ------------------------------------------------------------------
    multiIf(
        fs[1] = fs[2] and fs[2] = fs[3], 'monotone',
        fs[1] = fs[2] or fs[2] = fs[3] or fs[1] = fs[3], 'two_tone',
        'rainbow'
    )::LowCardinality(String)                                            as flop_suitedness,
    multiIf(
        fr[1] = fr[2] and fr[2] = fr[3], 'trips',
        fr[1] = fr[2] or fr[2] = fr[3] or fr[1] = fr[3], 'paired',
        'unpaired'
    )::LowCardinality(String)                                            as flop_pairing,
    substring('23456789TJQKA', fr_desc[1], 1)::LowCardinality(String)      as flop_high_card,
    toUInt8(fr_desc[1] - fr_desc[3])                                     as flop_span,
    multiIf(
        fr_desc[1] - fr_desc[3] <= 2, 'connected',
        fr_desc[1] - fr_desc[3] <= 4, 'semi_connected',
        'disconnected'
    )::LowCardinality(String)                                            as flop_connectedness,
    toUInt8(length(arrayDistinct(fr)) < length(fr))                      as paired_flop,
    toUInt8(arrayMax(arrayMap(s -> countEqual(fs, s), fs)) >= 3)                                           as flush_flop,
    toUInt8(arrayExists(
        l -> arrayCount(x -> x >= l and x <= l + 4,
                        arrayDistinct(arrayConcat(fr,
                                                  arrayMap(x -> toUInt64(0),
                                                           arrayFilter(x -> x = 13, fr))))) >= 3,
        range(toUInt64(0), toUInt64(10))
    ))                                        as straight_flop,

    -- ---- the turn ------------------------------------------------------------------
    if(has_turn, substring('23456789TJQKA', r4, 1), '')::LowCardinality(String) as turn_rank,
    toUInt8(has_turn and has(fr, r4))                                    as turn_pairs_board,
    toUInt8(has_turn and countEqual(ts, s4) >= 3)                        as turn_completes_flush,
    toUInt8(length(arrayDistinct(tr)) < length(tr))                      as paired_turn,
    toUInt8(arrayMax(arrayMap(s -> countEqual(ts, s), ts)) >= 3)                                           as flush_turn,
    toUInt8(arrayExists(
        l -> arrayCount(x -> x >= l and x <= l + 4,
                        arrayDistinct(arrayConcat(tr,
                                                  arrayMap(x -> toUInt64(0),
                                                           arrayFilter(x -> x = 13, tr))))) >= 3,
        range(toUInt64(0), toUInt64(10))
    ))                                        as straight_turn,

    -- ---- the river -----------------------------------------------------------------
    if(has_river, substring('23456789TJQKA', r5, 1), '')::LowCardinality(String) as river_rank,
    toUInt8(has_river and has(tr, r5))                                   as river_pairs_board,
    toUInt8(has_river and countEqual(rs, s5) >= 3 and countEqual(ts, s5) < 3) as river_completes_flush,
    toUInt8(length(arrayDistinct(rr)) < length(rr))                      as paired_river,
    toUInt8(arrayMax(arrayMap(s -> countEqual(rs, s), rs)) >= 3)                                           as flush_river,
    toUInt8(arrayExists(
        l -> arrayCount(x -> x >= l and x <= l + 4,
                        arrayDistinct(arrayConcat(rr,
                                                  arrayMap(x -> toUInt64(0),
                                                           arrayFilter(x -> x = 13, rr))))) >= 3,
        range(toUInt64(0), toUInt64(10))
    ))                                        as straight_river,

    -- ---- the board as dealt (hand-grain stats) ---------------------------------------
    toUInt8(length(arrayDistinct(rr)) < length(rr))                      as paired_final,
    toUInt8(arrayMax(arrayMap(s -> countEqual(rs, s), rs)) >= 3)                                           as flush_final
from parts
) as b
            on b.user_id = h.user_id and b.hand_uid = h.hand_uid
           and toYYYYMMDD(b.played_at_utc) in {partitions:Array(UInt32)} and b.user_id = {tenant:UInt32} and b.src_parsed_at = {stamp:DateTime64(3, 'UTC')}
        where toYYYYMMDD(h.played_at_utc) in {partitions:Array(UInt32)} and h.user_id = {tenant:UInt32} and h.src_parsed_at = {stamp:DateTime64(3, 'UTC')}
    ) as hb
    array join arrayEnumerate(hb.a_idx) as k
    where hb.a_tok[k] != 'p'
)
) AS fresh
WHERE fresh.hand_uid NOT IN (
    SELECT hand_uid FROM marts.decisions
    WHERE user_id = {tenant:UInt32} AND toYYYYMMDD(played_at_utc) IN {partitions:Array(UInt32)}
)
