-- GENERATED by `make gen` from dbt/poker_dwh (the macros and models named below) -- edit the dbt models, not this file.
-- The worker's derivation of one batch into marts.player_hands (plan E.1b, ADR-047):
-- models/marts/player_hands.sql rendered with the batch predicate in place of dbt's partition gate,
-- `int_board_by_street` inlined, and `built_by = 'hot'` so that dbt's gate knows the
-- partition is not its own work yet. Three parameters: tenant, stamp, partitions.
INSERT INTO marts.player_hands
SELECT * FROM (
-- One row per (hand, player): the hand-grain fact behind VPIP, PFR, WTSD, WWSF, W$SD and
-- bb/100 (ADR-020). ~35 columns, not 156: everything "facing X, did Y" lives on decisions.
--
-- Built by exploding the seat arrays of hand_arrays() (macros/hand_arrays.sql), so the only
-- join is at hand grain (the per-street board). Columns are the `player_hands` entries of
-- stats/registry/dimensions.yaml.



select
    hb.user_id                                                   as user_id,
    hb.dataset                                                   as dataset,
    hb.hand_uid                                                  as hand_uid,
    hb.played_at_utc                                             as played_at_utc,
    hb.played_date                                               as played_date,
    seat                                                         as seat,
    player_key                                                   as player_key,
    player_key_norm                                              as player_key_norm,
    is_hero                                                      as is_hero,
    is_anonymized                                                as is_anonymized,

    -- ---- table dimensions -----------------------------------------------------------
    hb.site                                                      as site,
    hb.stake_level                                               as stake_level,
    hb.game_type                                                 as game_type,
    hb.table_format                                              as table_format,
    hb.big_blind                                                 as big_blind,
    hb.players_dealt_in                                          as players_dealt_in,
    position::LowCardinality(String)                             as position,
    hb.pot_type                                                  as pot_type,
    hb.players_to_flop                                           as players_to_flop,

    -- ---- holding, depth, position ---------------------------------------------------
    hand_class::LowCardinality(String)                           as hand_class,
    hand_shape::LowCardinality(String)                           as hand_shape,
    hole_cards                                                   as hole_cards,
    stack_bb                                                     as stack_bb,
    toUInt8(saw_flop = 1 and hb.flop_last_seat = seat)           as is_ip,

    -- ---- the board (zero-padded to '' / 0 when no flop was dealt) --------------------
    hb.b_flop_suitedness::LowCardinality(String)                 as flop_suitedness,
    hb.b_flop_pairing::LowCardinality(String)                    as flop_pairing,
    hb.b_flop_high_card::LowCardinality(String)                  as flop_high_card,
    hb.b_flop_high_card_class::LowCardinality(String)            as flop_high_card_class,
    hb.b_flop_connectivity::LowCardinality(String)               as flop_connectivity,
    hb.b_flop_span                                               as flop_span,
    hb.b_paired_final                                            as board_paired_final,
    hb.b_flush_final                                             as board_flush_possible_final,

    -- ---- what happened --------------------------------------------------------------
    did_vpip                                                     as did_vpip,
    did_pfr                                                      as did_pfr,
    saw_flop                                                     as saw_flop,
    saw_turn                                                     as saw_turn,
    saw_river                                                    as saw_river,
    went_to_showdown                                             as went_to_showdown,
    won_hand                                                     as won_hand,
    net_won_bb                                                   as net_won_bb,
    ev_won_bb                                                    as ev_won_bb,
    if(went_to_showdown = 1, net_won_bb, toDecimal64(0, 4))      as showdown_won_bb,
    if(went_to_showdown = 1, toDecimal64(0, 4), net_won_bb)      as nonshowdown_won_bb,
    rake_paid_bb                                                 as rake_paid_bb,

    hb.parser_version                                            as parser_version,
    hb.src_parsed_at                                             as src_parsed_at,
    -- Last, always: see macros/provenance.sql and decision_state.sql (ADR-047).
    'hot'::LowCardinality(String)                                             as built_by
from (
    select
        h.*,
        b.flop_suitedness     as b_flop_suitedness,
        b.flop_pairing        as b_flop_pairing,
        b.flop_high_card      as b_flop_high_card,
        b.flop_high_card_class as b_flop_high_card_class,
        b.flop_connectivity   as b_flop_connectivity,
        b.flop_span           as b_flop_span,
        b.paired_final        as b_paired_final,
        b.flush_final         as b_flush_final
    from (with acts as (

    select
        user_id,
        hand_uid,
        action_index,
        seat,
        multiIf(street = 'preflop', 0, street = 'flop', 1, street = 'turn', 2, 3)::UInt8 as st,
        action_type,
        amount,
        amount_to,
        pot_before,
        to_call,
        is_allin,
        is_voluntary
    from staging.stg_actions
    where action_type in ('post_sb', 'post_bb', 'post_ante', 'post_straddle', 'post_dead',
                          'fold', 'check', 'call', 'bet', 'raise')
      and toYYYYMMDD(played_at_utc) in {partitions:Array(UInt32)} and user_id = {tenant:UInt32} and src_parsed_at = {stamp:DateTime64(3, 'UTC')}

),

hand_actions as (

    select
        user_id,
        hand_uid,
        arraySort(t -> t.1, groupArray((action_index, seat, st, action_type, amount, amount_to,
                                        pot_before, to_call, is_allin, is_voluntary))) as acts,
        -- Sentinel, not 0: with no raise every preflop call must count as a limp.
        if(countIf(st = 0 and action_type = 'raise') = 0, toUInt16(65535),
           minIf(action_index, st = 0 and action_type = 'raise'))            as first_raise_idx,
        toUInt8(countIf(st = 0 and action_type = 'raise'))                   as n_preflop_raises,
        argMinIf(seat, action_index, st = 0 and action_type = 'raise')       as opener_seat,
        argMaxIf(seat, action_index, st = 0 and action_type = 'raise')       as aggressor_seat,
        argMinIf(pot_before, action_index, st = 1)                           as pot_at_flop
    from acts
    group by user_id, hand_uid

),

seats_raw as (

    select
        user_id,
        hand_uid,
        seat,
        toString(position)                                       as position,
        player_key,
        coalesce(player_key, '')                                 as player_key_norm,
        is_hero,
        is_anonymized,
        toFloat32(starting_stack_bb)                             as stack_bb,
        hole_cards,
        net_won_bb,
        coalesce(ev_won_bb, net_won_bb)                          as ev_won_bb,
        saw_flop,
        saw_turn,
        saw_river,
        went_to_showdown,
        won_hand,
        total_invested,
        -- Written at parse time by core/classify.py; '' where the cards or the board were not
        -- known. SQL cannot rank a poker hand, which is why these are columns and not an
        -- expression here (plan E.5, ADR-018).
        made_hand_flop,
        made_hand_turn,
        made_hand_river,
        -- 'AKs' / 'T9o' / 'QQ' -- the 169-combo vocabulary. Hold'em-shaped hands only.
        splitByChar(' ', hole_cards)                             as cards,
        if(length(cards) = 2, position('23456789TJQKA', substring(cards[1], 1, 1)), 0) as r1,
        if(length(cards) = 2, position('23456789TJQKA', substring(cards[2], 1, 1)), 0) as r2,
        length(cards) = 2 and substring(cards[1], 2, 1) = substring(cards[2], 2, 1) as suited,
        multiIf(
            r1 = 0 or r2 = 0, '',
            r1 = r2, concat(substring('23456789TJQKA', r1, 1), substring('23456789TJQKA', r1, 1)),
            concat(substring('23456789TJQKA', greatest(r1, r2), 1),
                   substring('23456789TJQKA', least(r1, r2), 1),
                   if(suited, 's', 'o'))
        )                                                        as hand_class,
        multiIf(r1 = 0 or r2 = 0, '', r1 = r2, 'pair', suited, 'suited', 'offsuit') as hand_shape
    from staging.stg_hand_players
    where toYYYYMMDD(played_at_utc) in {partitions:Array(UInt32)} and user_id = {tenant:UInt32} and src_parsed_at = {stamp:DateTime64(3, 'UTC')}

),

seats as (

    select
        user_id,
        hand_uid,
        arraySort(t -> t.1, groupArray((seat, position, player_key, player_key_norm, is_hero,
                                        is_anonymized, stack_bb, hole_cards, hand_class,
                                        hand_shape, net_won_bb, ev_won_bb, saw_flop, saw_turn,
                                        saw_river, went_to_showdown, won_hand,
                                        total_invested, made_hand_flop, made_hand_turn,
                                        made_hand_river)))                 as seats,
        sum(total_invested)                                                as invested_total
    from seats_raw
    group by user_id, hand_uid

)

select
    h.user_id                                                    as user_id,
    h.dataset                                                    as dataset,
    h.hand_uid                                                   as hand_uid,
    h.played_at_utc                                              as played_at_utc,
    h.played_date                                                as played_date,
    h.src_parsed_at                                              as src_parsed_at,
    h.parser_version                                             as parser_version,
    h.site                                                       as site,
    h.stake_level                                                as stake_level,
    h.game_type                                                  as game_type,
    h.table_format                                               as table_format,
    h.big_blind                                                  as big_blind,
    h.players_dealt_in                                           as players_dealt_in,

    -- ---- the action stream ----------------------------------------------------------
    arrayMap(t -> t.1, a.acts)                                   as a_idx,
    arrayMap(t -> t.2, a.acts)                                   as a_seat,
    arrayMap(t -> t.3, a.acts)                                   as a_st,
    arrayMap(t -> multiIf(
        t.4 = 'fold', 'f',
        t.4 = 'check', 'x',
        t.4 = 'call' and t.3 = 0 and t.1 < a.first_raise_idx, 'l',
        t.4 = 'call', 'c',
        t.4 = 'bet', 'b',
        t.4 = 'raise', 'r',
        'p'), a.acts)                                            as a_tok,
    arrayMap(t -> toFloat32(toFloat64(t.5) / toFloat64(h.big_blind)), a.acts) as a_amt,
    arrayMap(t -> toFloat32(toFloat64(t.6) / toFloat64(h.big_blind)), a.acts) as a_to,
    arrayMap(t -> toFloat32(toFloat64(t.7) / toFloat64(h.big_blind)), a.acts) as a_pot,
    arrayMap(t -> toFloat32(toFloat64(t.8) / toFloat64(h.big_blind)), a.acts) as a_call,
    arrayMap(t -> t.9, a.acts)                                   as a_allin,
    arrayMap(t -> t.10, a.acts)                                  as a_vol,

    -- ---- hand-level preflop facts ---------------------------------------------------
    a.first_raise_idx                                            as first_raise_idx,
    a.n_preflop_raises                                           as n_preflop_raises,
    a.opener_seat                                                as opener_seat,
    a.aggressor_seat                                             as aggressor_seat,
    multiIf(
        a.n_preflop_raises = 0, 'limped',
        a.n_preflop_raises = 1, 'srp',
        a.n_preflop_raises = 2, '3bet',
        a.n_preflop_raises = 3, '4bet',
        '5bet_plus'
    )::LowCardinality(String)                                    as pot_type,
    toFloat32(toFloat64(a.pot_at_flop) / toFloat64(h.big_blind)) as pot_at_flop_bb,
    -- The seat whose FIRST flop action comes last acts last, i.e. is in position (v1's
    -- definition, kept for parity). arrayDistinct keeps first-occurrence order.
    arrayElement(arrayDistinct(arrayFilter((s, st, t) -> st = 1 and t != 'p',
                                           a_seat, a_st, a_tok)), -1) as flop_last_seat,

    -- ---- the seats ------------------------------------------------------------------
    arrayMap(t -> t.1, s.seats)                                  as s_seat,
    arrayMap(t -> t.2, s.seats)                                  as s_position,
    arrayMap(t -> t.3, s.seats)                                  as s_player_key,
    arrayMap(t -> t.4, s.seats)                                  as s_player_key_norm,
    arrayMap(t -> t.5, s.seats)                                  as s_is_hero,
    arrayMap(t -> t.6, s.seats)                                  as s_is_anonymized,
    arrayMap(t -> t.7, s.seats)                                  as s_stack_bb,
    arrayMap(t -> t.8, s.seats)                                  as s_hole_cards,
    arrayMap(t -> t.9, s.seats)                                  as s_hand_class,
    arrayMap(t -> t.10, s.seats)                                 as s_hand_shape,
    arrayMap(t -> t.11, s.seats)                                 as s_net_won_bb,
    arrayMap(t -> t.12, s.seats)                                 as s_ev_won_bb,
    arrayMap(t -> t.13, s.seats)                                 as s_saw_flop,
    arrayMap(t -> t.14, s.seats)                                 as s_saw_turn,
    arrayMap(t -> t.15, s.seats)                                 as s_saw_river,
    arrayMap(t -> t.16, s.seats)                                 as s_went_to_showdown,
    arrayMap(t -> t.17, s.seats)                                 as s_won_hand,
    arrayMap(t -> t.19, s.seats)                                 as s_made_hand_flop,
    arrayMap(t -> t.20, s.seats)                                 as s_made_hand_turn,
    arrayMap(t -> t.21, s.seats)                                 as s_made_hand_river,
    -- Rake attributed by contribution (the "weighted contributed" convention).
    arrayMap(t -> if(s.invested_total > 0,
                     toFloat32(toFloat64(h.rake) * toFloat64(t.18)
                               / toFloat64(s.invested_total) / toFloat64(h.big_blind)),
                     toFloat32(0)), s.seats)                     as s_rake_paid_bb,
    arrayMap(x -> toUInt8(arrayExists((s2, st, v) -> s2 = x and st = 0 and v = 1,
                                      a_seat, a_st, a_vol)), s_seat)  as s_did_vpip,
    arrayMap(x -> toUInt8(arrayExists((s2, st, t) -> s2 = x and st = 0 and t = 'r',
                                      a_seat, a_st, a_tok)), s_seat)  as s_did_pfr,
    toUInt8(arraySum(s_saw_flop))                                as players_to_flop
from staging.stg_hands as h
inner join hand_actions as a
    on a.user_id = h.user_id and a.hand_uid = h.hand_uid
inner join seats as s
    on s.user_id = h.user_id and s.hand_uid = h.hand_uid
where toYYYYMMDD(h.played_at_utc) in {partitions:Array(UInt32)} and h.user_id = {tenant:UInt32} and h.src_parsed_at = {stamp:DateTime64(3, 'UTC')}
) as h
    left join (
-- Board texture per hand, AT EACH STREET: what the board looked like when the flop, turn and
-- river decisions were made. A decision on the turn must see the turn card and not the river,
-- so every feature exists three times and marts/decisions.sql picks the one for its street.
--
-- Hands that never saw a flop have no row; the LEFT JOIN in the consumers zero-pads to '' / 0,
-- which is what the registry declares for "before the flop" (stats/registry/dimensions.yaml).
--
-- Ranks are 1..13 for 2..A via position() into one rank string, the same encoding as
-- macros/hand_arrays.sql uses for hole cards. Every classification is a macro in
-- macros/board.sql, so the fixture both test suites parse can be run through the same SQL
-- (plan H.3); this model only wires them to the columns.





with flop as (

    select
        user_id,
        hand_uid,
        played_at_utc,
        src_parsed_at,
        [board_flop_1, board_flop_2, board_flop_3]                as f,
        board_turn                                                as c4,
        board_river                                               as c5
    from staging.stg_hands
    where board_flop_1 != '' and toYYYYMMDD(played_at_utc) in {partitions:Array(UInt32)} and user_id = {tenant:UInt32} and src_parsed_at = {stamp:DateTime64(3, 'UTC')}

),

parts as (

    select
        user_id,
        hand_uid,
        played_at_utc,
        src_parsed_at,
        arrayMap(c -> position('23456789TJQKA', substring(c, 1, 1)), f)   as fr,
        arrayMap(c -> substring(c, 2, 1), f)                             as fs,
        arrayReverseSort(fr)                                             as fr_desc,
        c4 != ''                                                         as has_turn,
        c5 != ''                                                         as has_river,
        position('23456789TJQKA', substring(c4, 1, 1))                     as r4,
        substring(c4, 2, 1)                                              as s4,
        position('23456789TJQKA', substring(c5, 1, 1))                     as r5,
        substring(c5, 2, 1)                                              as s5,
        if(has_turn, arrayConcat(fr, [r4]), fr)                          as tr,
        if(has_turn, arrayConcat(fs, [s4]), fs)                          as ts,
        if(has_river, arrayConcat(tr, [r5]), tr)                         as rr,
        if(has_river, arrayConcat(ts, [s5]), ts)                         as rs
    from flop

)

select
    user_id                                                              as user_id,
    hand_uid                                                             as hand_uid,
    played_at_utc                                                        as played_at_utc,
    src_parsed_at                                                        as src_parsed_at,

    -- ---- the flop ------------------------------------------------------------------
    multiIf(
        fs[1] = fs[2] and fs[2] = fs[3], 'monotone',
        fs[1] = fs[2] or fs[2] = fs[3] or fs[1] = fs[3], 'two_tone',
        'rainbow'
    )::LowCardinality(String)                  as flop_suitedness,
    multiIf(
        fr[1] = fr[2] and fr[2] = fr[3], 'trips',
        fr[1] = fr[2] or fr[2] = fr[3] or fr[1] = fr[3], 'paired',
        'unpaired'
    )::LowCardinality(String)                     as flop_pairing,
    substring('23456789TJQKA', fr_desc[1], 1)::LowCardinality(String)      as flop_high_card,
    multiIf(
        arrayMax(fr) = 13, 'ace',
        arrayMax(fr) >= 11, 'king_queen',
        arrayMax(fr) >= 9, 'jack_ten',
        arrayMax(fr) >= 6, 'middle',
        'low'
    )::LowCardinality(String)             as flop_high_card_class,
    multiIf(
        toUInt8(arrayMax(arrayMap(
        l -> arrayCount(x -> x >= l and x <= l + 4, arrayDistinct(arrayConcat(fr,
                              arrayMap(x -> toUInt64(0), arrayFilter(x -> x = 13, fr))))),
        range(toUInt64(0), toUInt64(10))
    )) >= 3) = 1, 'connected',
        toUInt8(arrayExists(
        l -> arrayCount(x -> x >= l and x <= l + 3, arrayDistinct(arrayConcat(fr,
                              arrayMap(x -> toUInt64(0), arrayFilter(x -> x = 13, fr))))) >= 2,
        range(toUInt64(1), toUInt64(10))
    )) = 1, 'oesd',
        'disconnected'
    )::LowCardinality(String)                as flop_connectivity,
    toUInt8(fr_desc[1] - fr_desc[3])                                     as flop_span,
    toUInt8(length(arrayDistinct(fr)) < length(fr))                      as paired_flop,
    toUInt8(arrayMax(arrayMap(s -> countEqual(fs, s), fs)) >= 3)                                           as flush_flop,
    toUInt8(arrayMax(arrayMap(
        l -> arrayCount(x -> x >= l and x <= l + 4, arrayDistinct(arrayConcat(fr,
                              arrayMap(x -> toUInt64(0), arrayFilter(x -> x = 13, fr))))),
        range(toUInt64(0), toUInt64(10))
    )) >= 3)                                        as straight_flop,

    -- ---- the turn ------------------------------------------------------------------
    if(has_turn, substring('23456789TJQKA', r4, 1), '')::LowCardinality(String) as turn_rank,
    toUInt8(has_turn and has(fr, r4))                                    as turn_pairs_board,
    toUInt8(has_turn and countEqual(ts, s4) >= 3)                        as turn_completes_flush,
    if(has_turn, multiIf(
        countEqual(fs, s4) >= 2, 'turn_flush',
        arrayMax(arrayMap(
        l -> arrayCount(x -> x >= l and x <= l + 4, arrayDistinct(arrayConcat(arrayConcat(fr, [r4]),
                              arrayMap(x -> toUInt64(0), arrayFilter(x -> x = 13, arrayConcat(fr, [r4])))))),
        range(toUInt64(0), toUInt64(10))
    )) >= 3
            and arrayMax(arrayMap(
        l -> arrayCount(x -> x >= l and x <= l + 4, arrayDistinct(arrayConcat(arrayConcat(fr, [r4]),
                              arrayMap(x -> toUInt64(0), arrayFilter(x -> x = 13, arrayConcat(fr, [r4])))))),
        range(toUInt64(0), toUInt64(10))
    ))
                > arrayMax(arrayMap(
        l -> arrayCount(x -> x >= l and x <= l + 4, arrayDistinct(arrayConcat(fr,
                              arrayMap(x -> toUInt64(0), arrayFilter(x -> x = 13, fr))))),
        range(toUInt64(0), toUInt64(10))
    )), 'turn_straight',
        has(fr, r4), 'turn_pair',
        countEqual(fs, s4) = 1, 'turn_flush_draw',
        r4 > arrayMax(fr), 'turn_overcard',
        'turn_blank'
    ), '')::LowCardinality(String)
                                                                         as turn_change,
    toUInt8(length(arrayDistinct(tr)) < length(tr))                      as paired_turn,
    toUInt8(arrayMax(arrayMap(s -> countEqual(ts, s), ts)) >= 3)                                           as flush_turn,
    toUInt8(arrayMax(arrayMap(
        l -> arrayCount(x -> x >= l and x <= l + 4, arrayDistinct(arrayConcat(tr,
                              arrayMap(x -> toUInt64(0), arrayFilter(x -> x = 13, tr))))),
        range(toUInt64(0), toUInt64(10))
    )) >= 3)                                        as straight_turn,

    -- ---- the river -----------------------------------------------------------------
    if(has_river, substring('23456789TJQKA', r5, 1), '')::LowCardinality(String) as river_rank,
    toUInt8(has_river and has(tr, r5))                                   as river_pairs_board,
    toUInt8(has_river and countEqual(rs, s5) >= 3 and countEqual(ts, s5) < 3) as river_completes_flush,
    if(has_river, multiIf(
        countEqual(ts, s5) >= 2, 'river_flush',
        arrayMax(arrayMap(
        l -> arrayCount(x -> x >= l and x <= l + 4, arrayDistinct(arrayConcat(arrayConcat(tr, [r5]),
                              arrayMap(x -> toUInt64(0), arrayFilter(x -> x = 13, arrayConcat(tr, [r5])))))),
        range(toUInt64(0), toUInt64(10))
    )) >= 3
            and arrayMax(arrayMap(
        l -> arrayCount(x -> x >= l and x <= l + 4, arrayDistinct(arrayConcat(arrayConcat(tr, [r5]),
                              arrayMap(x -> toUInt64(0), arrayFilter(x -> x = 13, arrayConcat(tr, [r5])))))),
        range(toUInt64(0), toUInt64(10))
    ))
                > arrayMax(arrayMap(
        l -> arrayCount(x -> x >= l and x <= l + 4, arrayDistinct(arrayConcat(tr,
                              arrayMap(x -> toUInt64(0), arrayFilter(x -> x = 13, tr))))),
        range(toUInt64(0), toUInt64(10))
    )), 'river_straight',
        has(tr, r5), 'river_pair',
        r5 > arrayMax(tr), 'river_overcard',
        'river_blank'
    ), '')::LowCardinality(String)
                                                                         as river_change,
    toUInt8(length(arrayDistinct(rr)) < length(rr))                      as paired_river,
    toUInt8(arrayMax(arrayMap(s -> countEqual(rs, s), rs)) >= 3)                                           as flush_river,
    toUInt8(arrayMax(arrayMap(
        l -> arrayCount(x -> x >= l and x <= l + 4, arrayDistinct(arrayConcat(rr,
                              arrayMap(x -> toUInt64(0), arrayFilter(x -> x = 13, rr))))),
        range(toUInt64(0), toUInt64(10))
    )) >= 3)                                        as straight_river,

    -- ---- the board as dealt (hand-grain stats) ---------------------------------------
    toUInt8(length(arrayDistinct(rr)) < length(rr))                      as paired_final,
    toUInt8(arrayMax(arrayMap(s -> countEqual(rs, s), rs)) >= 3)                                           as flush_final
from parts
) as b
        on b.user_id = h.user_id and b.hand_uid = h.hand_uid
       and toYYYYMMDD(b.played_at_utc) in {partitions:Array(UInt32)} and b.user_id = {tenant:UInt32} and b.src_parsed_at = {stamp:DateTime64(3, 'UTC')}
    where toYYYYMMDD(h.played_at_utc) in {partitions:Array(UInt32)} and h.user_id = {tenant:UInt32} and h.src_parsed_at = {stamp:DateTime64(3, 'UTC')}
) as hb
array join
    hb.s_seat             as seat,
    hb.s_position         as position,
    hb.s_player_key       as player_key,
    hb.s_player_key_norm  as player_key_norm,
    hb.s_is_hero          as is_hero,
    hb.s_is_anonymized    as is_anonymized,
    hb.s_stack_bb         as stack_bb,
    hb.s_hole_cards       as hole_cards,
    hb.s_hand_class       as hand_class,
    hb.s_hand_shape       as hand_shape,
    hb.s_net_won_bb       as net_won_bb,
    hb.s_ev_won_bb        as ev_won_bb,
    hb.s_saw_flop         as saw_flop,
    hb.s_saw_turn         as saw_turn,
    hb.s_saw_river        as saw_river,
    hb.s_went_to_showdown as went_to_showdown,
    hb.s_won_hand         as won_hand,
    hb.s_rake_paid_bb     as rake_paid_bb,
    hb.s_did_vpip         as did_vpip,
    hb.s_did_pfr          as did_pfr
) AS fresh
WHERE fresh.hand_uid NOT IN (
    SELECT hand_uid FROM marts.player_hands
    WHERE user_id = {tenant:UInt32} AND toYYYYMMDD(played_at_utc) IN {partitions:Array(UInt32)}
)
