-- GENERATED by `make gen` from stats/registry -- edit the registry, not this file.
-- LAW OF ARITHMETIC: an action can never be counted more often than the opportunity
-- that allowed it. Every cached stat is action / opportunity, so a violation means the
-- opportunity predicate is narrower than the action predicate for some rows.

{% set pairs = [
    ('bb_per_100_action', 'bb_per_100_opp'),
    ('ev_bb_per_100_action', 'ev_bb_per_100_opp'),
    ('sd_bb_per_100_action', 'sd_bb_per_100_opp'),
    ('nsd_bb_per_100_action', 'nsd_bb_per_100_opp'),
    ('cbet_flop_action', 'cbet_flop_opp'),
    ('cbet_turn_action', 'cbet_turn_opp'),
    ('cbet_river_action', 'cbet_river_opp'),
    ('delayed_cbet_action', 'delayed_cbet_opp'),
    ('fold_to_cbet_flop_action', 'fold_to_cbet_flop_opp'),
    ('call_cbet_flop_action', 'call_cbet_flop_opp'),
    ('raise_cbet_flop_action', 'raise_cbet_flop_opp'),
    ('fold_to_cbet_turn_action', 'fold_to_cbet_turn_opp'),
    ('fold_to_cbet_river_action', 'fold_to_cbet_river_opp'),
    ('fold_to_delayed_cbet_action', 'fold_to_delayed_cbet_opp'),
    ('float_flop_action', 'float_flop_opp'),
    ('float_fold_action', 'float_fold_opp'),
    ('donk_flop_action', 'donk_flop_opp'),
    ('fold_to_donk_action', 'fold_to_donk_opp'),
    ('probe_turn_action', 'probe_turn_opp'),
    ('fold_to_probe_turn_action', 'fold_to_probe_turn_opp'),
    ('probe_river_action', 'probe_river_opp'),
    ('fold_to_probe_river_action', 'fold_to_probe_river_opp'),
    ('check_raise_flop_action', 'check_raise_flop_opp'),
    ('check_raise_turn_action', 'check_raise_turn_opp'),
    ('check_raise_river_action', 'check_raise_river_opp'),
    ('fold_to_flop_raise_action', 'fold_to_flop_raise_opp'),
    ('fold_to_turn_raise_action', 'fold_to_turn_raise_opp'),
    ('fold_to_river_raise_action', 'fold_to_river_raise_opp'),
    ('bet_call_river_action', 'bet_call_river_opp'),
    ('river_raise_action', 'river_raise_opp'),
    ('river_check_fold_action', 'river_check_fold_opp'),
    ('river_check_call_action', 'river_check_call_opp'),
    ('vpip_action', 'vpip_opp'),
    ('pfr_action', 'pfr_opp'),
    ('rfi_action', 'rfi_opp'),
    ('steal_action', 'steal_opp'),
    ('limp_action', 'limp_opp'),
    ('iso_raise_action', 'iso_raise_opp'),
    ('cold_call_action', 'cold_call_opp'),
    ('defend_vs_open_action', 'defend_vs_open_opp'),
    ('fold_vs_open_action', 'fold_vs_open_opp'),
    ('threebet_action', 'threebet_opp'),
    ('squeeze_action', 'squeeze_opp'),
    ('fold_to_3bet_action', 'fold_to_3bet_opp'),
    ('call_3bet_action', 'call_3bet_opp'),
    ('fourbet_action', 'fourbet_opp'),
    ('fold_to_4bet_action', 'fold_to_4bet_opp'),
    ('call_4bet_action', 'call_4bet_opp'),
    ('fivebet_action', 'fivebet_opp'),
    ('fold_bb_to_steal_action', 'fold_bb_to_steal_opp'),
    ('limp_fold_action', 'limp_fold_opp'),
    ('limp_call_action', 'limp_call_opp'),
    ('limp_raise_action', 'limp_raise_opp'),
    ('wwsf_action', 'wwsf_opp'),
    ('wtsd_action', 'wtsd_opp'),
    ('wsd_action', 'wsd_opp'),
] %}

with totals as (
    select
        user_id,
        dataset,
        {%- for action, opp in pairs %}
        sum({{ action }}) as {{ action }}__a,
        sum({{ opp }}) as {{ opp }}__o{{ "," if not loop.last }}
        {%- endfor %}
    from {{ ref('stats_daily_v2') }}
    group by user_id, dataset
)

select * from totals
where
    {%- for action, opp in pairs %}
    {{ action }}__a > {{ opp }}__o{{ " or" if not loop.last }}
    {%- endfor %}
