/**
 * The controls you act with rather than read through: the hand list's tag, the replayer, the
 * analyzer's rail and gate, the trainers, the grids, the range screens and the upload.
 */
import type { ControlHelp } from './types';
import { APP, UI } from './types';

export const DOING_CONTROLS: readonly ControlHelp[] = [
  {
    id: 'hand-tags',
    anchor: '[data-testid="hands-tag-filter"]',
    source: `${APP}/pages/hands/index.vue`,
    control: 'Tagged',
    does: 'Keeps only hands you have given this tag. It narrows on top of the situation rather than instead of it.',
    where: 'The hand list.',
  },
  {
    id: 'replay-transport',
    anchor: '[data-testid="replay-seek"]',
    source: `${UI}/HandReplayer.vue`,
    control: 'The replayer transport',
    does: 'Moves through the hand one decision at a time. Back, next and play do the same thing at different speeds; the street buttons jump, and the number keys 1–4 pick a street.',
    where: 'Any replayed hand.',
  },
  {
    id: 'study-node',
    anchor: '[data-testid="study-node"]',
    source: `${APP}/components/hands/HandStudy.vue`,
    control: 'The situation line',
    does: 'Names the spot the hand is standing in right now. Every panel below is bound to it, so stepping forward rebinds them all rather than re-reading the whole hand.',
    where: 'The replayer, above the panels.',
  },
  {
    id: 'reveal-group',
    anchor: '[data-testid="reveal-group"]',
    source: `${APP}/components/hands/RangeReveal.vue`,
    control: 'Compare the field with',
    does: 'Chooses one of the pool’s player groups — regs, fish, the rest, the unknowns — or one of your saved cohorts to reveal beside the whole field, so the diff is drawn twice: once against everyone and once against that group. The field is always asked; the group is asked after it.',
    where: 'The replayer, under your read.',
  },
  {
    id: 'reveal-button',
    anchor: '[data-testid="reveal-button"]',
    source: `${APP}/components/hands/RangeReveal.vue`,
    control: 'Reveal the pool’s range',
    does: 'Asks the pool what the acting seat turned over at this exact spot and draws it as a difference from the range you painted. It stays off until you have painted something, and nothing is asked before you press it.',
    where: 'The replayer, under your read.',
  },
  {
    id: 'blockers-ask',
    anchor: '[data-testid="blockers-ask"]',
    source: `${APP}/components/hands/PoolBlockers.vue`,
    control: 'Ask the pool how the defender answers',
    does: 'Asks the pool how often the seat facing this bet folds here, cuts your chart for that seat at that share by its equity against the bettor’s range, and ranks the bettor’s own hands by what they block. The rate is measured; the ordering is a rule of thumb, which the panel says.',
    where: 'The replayer, beside the pot-odds panels, at a step where a bet was just made.',
  },
  {
    id: 'blocker-rows',
    anchor: '[data-testid="blocker-rows"]',
    source: `${UI}/BlockerPanel.vue`,
    control: 'The ranked rows',
    does: 'Where a row’s hand is a button, pressing it pins that row — the table then says what the hand removes from the calls and the folds — and, where a grid stands beside the table, rings the hand there too. It changes nothing that is graded.',
    where: 'The blocker table, in the replayer, the Range Lab, the analyzer’s step 8 and the blocker trainer.',
  },
  {
    id: 'stepper',
    anchor: '[data-testid="stepper"]',
    source: `${UI}/StepperNav.vue`,
    control: 'The step rail',
    does: 'Moves between the nine steps and shows which you have committed. The steps build on each other, so an early one left blank leaves the later ones with nothing to work from.',
    where: 'The analyzer and the examples.',
  },
  {
    id: 'prediction-gate',
    anchor: '[data-testid="prediction-gate"]',
    source: `${UI}/PredictionGate.vue`,
    control: 'Your call',
    does: 'Takes your answer before the computed one exists: nothing is asked for until you commit, so there is nothing to look up first. Committing reveals the answer and scores the gap.',
    where: 'Every step of the analyzer, the examples and the trainers.',
  },
  {
    id: 'train-modes',
    anchor: '[data-testid^="mode-"]',
    source: `${APP}/pages/train/index.vue`,
    control: 'A training mode',
    does: 'Starts a run of that drill. The badge is how many spots are overdue today; what you got wrong comes back sooner than what you got right.',
    where: 'Train.',
  },
  {
    id: 'brush',
    anchor: '[data-testid^="brush-"]',
    source: `${APP}/components/train/DrawingTrainer.vue`,
    control: 'The brush',
    does: 'Sets the weight painted into a cell, so a range can hold part of a hand class rather than all of it — a quarter-weight cell is played this way a quarter of the time.',
    where: 'The range-drawing trainer, and beside the Range Lab’s grids.',
  },
  {
    id: 'range-matrix',
    anchor: '.pk-matrix',
    source: `${UI}/RangeMatrix.vue`,
    control: 'The hand grid',
    does: 'Reads a range and, where it can be edited, paints one: drag to fill with the brush, drag across filled cells to clear them. Tab into it and the arrow keys move, Enter or Space fills, and ⌘Z / ⌘⇧Z undo and redo a stroke.',
    where: 'The Range Lab, a stored range, Compare, step 1 and the drawing trainer.',
  },
  {
    id: 'node-editor',
    anchor: '[data-testid="node-label"]',
    source: `${UI}/NodeKeyEditor.vue`,
    control: 'The situation',
    does: 'Reads out the situation the boxes below describe — seats, street, action, stack, stake. A stored chart is found only where this matches to the last step, which is why it is spelled out in full.',
    where: 'Compare ranges, a stored range and the import review.',
  },
  {
    id: 'compare-pick',
    anchor: '[data-testid="compare-pick"]',
    source: `${APP}/pages/ranges/compare.vue`,
    control: 'Pick a situation from the library',
    does: 'Sets the situation above to one you already have a chart for, which saves building it by hand only to find the column empty.',
    where: 'Compare ranges.',
  },
  {
    id: 'compare-columns',
    anchor: '[data-testid="compare-columns"]',
    source: `${APP}/pages/ranges/compare.vue`,
    control: 'The three columns',
    does: 'Your own chart, a solver export of yours, and the field’s showdown range here. The first two are what you stored; the third is what was actually turned over.',
    where: 'Compare ranges.',
  },
  {
    id: 'compare-tier3',
    anchor: '[data-testid="compare-tier3"]',
    source: `${APP}/pages/ranges/compare.vue`,
    control: 'The reconstruction',
    does: 'Takes the chart in the first column as an assumption and reweights it by how over-represented each hand class is among the hands that took this action. It moves your prior; it does not read their range.',
    where: 'Compare ranges, under the columns.',
  },
  {
    id: 'upload-dataset',
    anchor: '[data-testid^="upload-dataset-"]',
    source: `${APP}/pages/upload/index.vue`,
    control: 'My hands / Pool hands',
    does: 'Decides what the files become: your own play, counted through your seat, or observed tables whose every seat joins the pool. A file belongs to one of them for good.',
    where: 'Upload, above the drop zone.',
  },
  {
    id: 'upload-drop',
    anchor: '[data-testid="upload-drop"]',
    source: `${APP}/components/upload/DropZone.vue`,
    control: 'The drop zone',
    does: 'Takes files or a whole folder, dropped or picked, and starts sending them under the dataset and site chosen above — which stay locked until the last one is sent.',
    where: 'Upload.',
  },
  {
    id: 'upload-list',
    anchor: '[data-testid="upload-list"]',
    source: `${APP}/components/upload/UploadList.vue`,
    control: 'Recent uploads',
    does: 'The server’s own record of each file and how far it got. A row that sits waiting rather than reaching completed means the parser worker is not running.',
    where: 'Upload, under the queue.',
  },
  {
    id: 'import-apply-all',
    anchor: '[data-testid="import-apply-all"]',
    source: `${APP}/pages/ranges/import.vue`,
    control: 'Apply to all',
    does: 'Writes the source, tool and tags in the boxes beside it onto every row of the review. The boxes alone change nothing until this is pressed.',
    where: 'Import ranges, above the review table.',
  },
  {
    id: 'import-conflict',
    anchor: '[data-testid="import-conflict"]',
    source: `${APP}/pages/ranges/import.vue`,
    control: 'If the name is taken',
    does: 'Decides what happens to a name your library already has: keep both, add a version to the chart that is there, or skip the incoming one.',
    where: 'Import ranges, beside the commit button.',
  },
  {
    id: 'heuristic-street',
    anchor: '[data-testid="heuristic-street"]',
    source: `${APP}/components/train/HeuristicLog.vue`,
    control: 'The street',
    does: 'Files the heuristic you are writing under the street it is about, which is how the log asks you about it again a fortnight later.',
    where: 'Progress, in the heuristic log.',
  },
];
