"""Render the dbt staging models from the table specs.

A staging model is a view over one core table with `FINAL`, projecting every column plus a few
derived ones (`played_date`, the street-reached flags, the watermark alias). Generated so that
a column added to the spec reaches dbt automatically; `make gen` writes the files and
`make gen-check` (part of `make check`) fails when they are stale.
"""

from __future__ import annotations

from core.schema.base import TableSpec

HEADER = (
    "-- GENERATED by `make gen` from core/schema/{module}.py -- edit the spec, not this file.\n"
    "-- {doc}\n"
    "--\n"
    "-- `FINAL` is load-bearing, not decoration: every core table is a ReplacingMergeTree, so\n"
    "-- after a re-parse there are temporarily TWO physical rows per key until a background\n"
    "-- merge collapses them. Merges are eventual. Without FINAL, every hand counts twice\n"
    "-- during that window.\n"
)


def render_staging_model(spec: TableSpec, module: str) -> str:
    """The full SQL text of `stg_<table>.sql` for one spec."""
    projections = [c.staging_expr or c.name for c in spec.columns]
    projections.extend(spec.staging_extras)
    body = ",\n".join(f"    {p}" for p in projections)
    return (
        HEADER.format(module=module, doc=spec.doc)
        + "\n"
        + "select\n"
        + body
        + "\n"
        + f"from {{{{ source('core', '{spec.name}') }}}} final\n"
    )
