name: shop_dwh
version: "1.0.0"
config-version: 2
profile: shop_dwh

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  shop_dwh:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
