-- GENERATED by `make gen` from core/schema/winners.py -- edit the spec, not this file.
-- One row per (pot, winning seat). pot_index 0 is the main pot.
--
-- `FINAL` is load-bearing, not decoration: every core table is a ReplacingMergeTree, so
-- after a re-parse there are temporarily TWO physical rows per key until a background
-- merge collapses them. Merges are eventual. Without FINAL, every hand counts twice
-- during that window.

select
    user_id,
    dataset,
    hand_uid,
    played_at_utc,
    pot_index,
    seat,
    amount_won,
    parsed_at,
    toDate(played_at_utc) as played_date,
    parsed_at as src_parsed_at
from {{ source('core', 'pot_winners') }} final
