-- GENERATED by `make gen` from core/schema/actions.py -- edit the spec, not this file.
-- One row per decision. The largest table and the one all stat logic reads.
--
-- `FINAL` is load-bearing, not decoration: every core table is a ReplacingMergeTree, so
-- after a re-parse there are temporarily TWO physical rows per key until a background
-- merge collapses them. Merges are eventual. Without FINAL, every hand counts twice
-- during that window.

select
    user_id,
    dataset,
    hand_uid,
    played_at_utc,
    action_index,
    toString(street) as street,
    seat,
    toString(action_type) as action_type,
    amount,
    amount_to,
    pot_before,
    to_call,
    is_allin,
    is_voluntary,
    parsed_at,
    cards_revealed,
    toDate(played_at_utc) as played_date,
    action_type in ('fold', 'check', 'call', 'bet', 'raise') as is_decision,
    parsed_at as src_parsed_at
from {{ source('core', 'actions') }} final
