-- GENERATED by `make gen` from core/schema/players.py -- edit the spec, not this file.
-- One row per occupied seat per hand.
--
-- `FINAL` is load-bearing, not decoration: every core table is a ReplacingMergeTree, so
-- after a re-parse there are temporarily TWO physical rows per key until a background
-- merge collapses them. Merges are eventual. Without FINAL, every hand counts twice
-- during that window.

select
    user_id,
    dataset,
    hand_uid,
    played_at_utc,
    seat,
    player_key,
    screen_name,
    is_hero,
    is_anonymized,
    anon_alias,
    position,
    position_index,
    starting_stack,
    starting_stack_bb,
    hole_cards,
    total_invested,
    net_won,
    net_won_bb,
    allin_equity,
    ev_won_bb,
    saw_flop,
    saw_turn,
    saw_river,
    went_to_showdown,
    won_hand,
    parsed_at,
    bounty_won,
    was_eliminated,
    finish_position,
    extra,
    made_hand_flop,
    made_hand_turn,
    made_hand_river,
    toDate(played_at_utc) as played_date,
    parsed_at as src_parsed_at
from {{ source('core', 'hand_players') }} final
