"""Write the files derived from the stat registry (`make gen`), or check them (`--check`).

    uv run python -m scripts.gen_stats            # rewrite the three generated files
    uv run python -m scripts.gen_stats --check    # exit 1 if any file differs (CI)

Generated (ADR-021), each carrying a `GENERATED` header and never edited by hand:
  dbt/poker_dwh/models/marts/stats_daily_v2.sql       the daily rollup: one `<code>_opp` /
                                                      `<code>_action` pair per `cached` stat,
                                                      decision-grain from `decisions`, hand-grain
                                                      from `player_hands`, UNION ALL on the keys
  dbt/poker_dwh/seeds/stat_definitions.csv            labels, categories, typical ranges
  dbt/poker_dwh/tests/assert_v2_action_le_opportunity.sql
                                                      the law of arithmetic for EVERY pair

`stats_daily_v2` is named so because the hand-written v1 `stats_daily` still serves the API
until plan C.5 switches the routes; C.6 deletes the v1 chain and drops the suffix.
"""

from __future__ import annotations

import argparse
import csv
import io
import sys
from pathlib import Path

from stats.compiler import Compiler, Literals
from stats.definitions import Stat, Table
from stats.registry import Registry, registry

PROJECT = Path(__file__).resolve().parent.parent / "dbt" / "poker_dwh"
ROLLUP = "stats_daily_v2"
HEADER = "-- GENERATED by `make gen` from stats/registry -- edit the registry, not this file."

KEYS = (
    ("user_id", "user_id"),
    ("dataset", "dataset"),
    ("player_key_norm", "player_key"),
    ("played_date", "day"),
    ("site", "site"),
    ("stake_level", "stake_level"),
    ("game_type", "game_type"),
    ("table_format", "table_format"),
    ("position", "position"),
    ("is_hero", "is_hero"),
    ("is_anonymized", "is_anonymized"),
)
"""(source column, rollup column). Every one of them is in the ORDER BY: SummingMergeTree
merges rows that share the sort key, so a group key outside it would collapse two groups into
one (docs/POKER_AUDIT.md B5)."""

ZERO_COUNT = "toUInt64(0)"
ZERO_MONEY = "toDecimal128(0, 4)"
SEED_COLUMNS = (
    "code", "label", "category", "grain", "format", "higher_is_better",
    "typical_low", "typical_high", "cached", "description", "notes",
)  # fmt: skip


def rollup_columns(stat: Stat, compiler: Compiler) -> list[tuple[str, str, str]]:
    """(column, expression on the stat's own table, zero for the other table) per stat.

    A ratio stat yields its `_opp` / `_action` pair; a bare count yields one column named
    after the stat (`hands`). Sums are widened to Decimal(38, 4) so both UNION branches agree
    on the type whatever the source column is.
    """
    numerator = compiler.expr(stat.numerator_expr)
    if stat.denominator_expr is None:
        return [(stat.code, numerator, ZERO_COUNT)]
    denominator = compiler.expr(stat.denominator_expr)
    return [
        (f"{stat.code}_opp", denominator, _zero(denominator)),
        (f"{stat.code}_action", numerator, _zero(numerator)),
    ]


def _zero(expression: str) -> str:
    return ZERO_MONEY if expression.startswith("sum(") else ZERO_COUNT


def _widen_sums(expression: str) -> str:
    """`sum(x)` -> `sum(toDecimal128(x, 4))`, so Decimal and Float sources land in one type."""
    if expression.startswith("sum(") and expression.endswith(")"):
        return f"sum(toDecimal128({expression[4:-1]}, 4))"
    return expression


def _branch(reg: Registry, table: Table, ref: str) -> str:
    """One UNION ALL branch: the keys, every cached stat's columns, the watermark."""
    lines = [
        f"    {source}{'' if source == target else ' as ' + target}," for source, target in KEYS
    ]
    for stat in reg.stats.values():
        if not stat.cached:
            continue
        own = Compiler(dims=reg.dimensions, table=stat.table, values=Literals())
        for column, expression, zero in rollup_columns(stat, own):
            value = _widen_sums(expression) if stat.table == table else zero
            lines.append(f"    {value} as {column},")
    lines.append("    max(src_parsed_at) as src_parsed_at")
    group_by = ", ".join(target for _, target in KEYS)
    return (
        "select\n"
        + "\n".join(lines)
        + f"\nfrom {{{{ ref('{ref}') }}}}\nwhere {{{{ dirty_partitions('played_at_utc') }}}}"
        + f"\ngroup by {group_by}"
    )


def render_rollup(reg: Registry) -> str:
    """The generated `stats_daily_v2` model."""
    order_by = ", ".join(target for _, target in KEYS)
    config = (
        "{{\n  config(\n    materialized='incremental',\n"
        "    incremental_strategy='insert_overwrite',\n    engine='SummingMergeTree()',\n"
        f"    order_by='({order_by})',\n    partition_by='toYYYYMMDD(day)',\n  )\n}}}}\n"
    )
    doc = (
        "-- The daily stat rollup (POKER_PLAN.md §2.3, ADR-021): every group key is in the ORDER\n"
        "-- BY, one opportunity / action pair per `cached` stat. Decision-grain stats are counted\n"
        "-- on `decisions`, hand-grain on `player_hands`; the two branches zero-fill each other's\n"
        "-- columns and SummingMergeTree adds rows sharing a key, so `sum(x)` is exact before and\n"
        "-- after merges. Adding a stat is one registry entry and `make gen`.\n"
    )
    return (
        f"{HEADER}\n{doc}\n{config}\n"
        + _branch(reg, "decisions", "decisions")
        + "\n\nunion all\n\n"
        + _branch(reg, "player_hands", "player_hands")
        + "\n"
    )


def render_seed(reg: Registry) -> str:
    """`stat_definitions.csv`: what the UI and the API need to describe a stat."""
    out = io.StringIO()
    writer = csv.writer(out, lineterminator="\n")
    writer.writerow(SEED_COLUMNS)
    for stat in reg.stats.values():
        low, high = stat.typical if stat.typical is not None else (None, None)
        better = "" if stat.higher_is_better is None else int(stat.higher_is_better)
        writer.writerow(
            [
                stat.code,
                stat.label,
                stat.category,
                stat.grain,
                stat.format,
                better,
                "" if low is None else low,
                "" if high is None else high,
                int(stat.cached),
                stat.description,
                stat.notes,
            ]
        )
    return out.getvalue()


def render_law_test(reg: Registry) -> str:
    """The v2 law test: no `_action` may exceed its `_opp`, for every cached pair."""
    pairs = [
        f"    ('{stat.code}_action', '{stat.code}_opp'),"
        for stat in reg.stats.values()
        if stat.cached and stat.denominator_expr is not None
    ]
    return (
        f"{HEADER}\n"
        "-- LAW OF ARITHMETIC: an action can never be counted more often than the opportunity\n"
        "-- that allowed it. Every cached stat is action / opportunity, so a violation means the\n"
        "-- opportunity predicate is narrower than the action predicate for some rows.\n\n"
        "{% set pairs = [\n" + "\n".join(pairs) + "\n] %}\n\n"
        "with totals as (\n    select\n        user_id,\n        dataset,\n"
        "        {%- for action, opp in pairs %}\n"
        "        sum({{ action }}) as {{ action }}__a,\n"
        '        sum({{ opp }}) as {{ opp }}__o{{ "," if not loop.last }}\n'
        "        {%- endfor %}\n"
        f"    from {{{{ ref('{ROLLUP}') }}}}\n    group by user_id, dataset\n)\n\n"
        "select * from totals\nwhere\n"
        "    {%- for action, opp in pairs %}\n"
        '    {{ action }}__a > {{ opp }}__o{{ " or" if not loop.last }}\n'
        "    {%- endfor %}\n"
    )


def expected_files(reg: Registry, project: Path = PROJECT) -> dict[Path, str]:
    """Path -> content for every generated file."""
    return {
        project / "models" / "marts" / f"{ROLLUP}.sql": render_rollup(reg),
        project / "seeds" / "stat_definitions.csv": render_seed(reg),
        project / "tests" / "assert_v2_action_le_opportunity.sql": render_law_test(reg),
    }


def _display(path: Path) -> Path:
    """The path relative to `platform/` when it is under it (tests render elsewhere)."""
    root = PROJECT.parents[1]
    return path.relative_to(root) if path.is_relative_to(root) else path


def main(argv: list[str] | None = None) -> int:
    """Write or check the generated files."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail instead of writing")
    args = ap.parse_args(argv)

    stale = []
    for path, content in expected_files(registry()).items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {_display(path)}")

    if args.check and stale:
        names = ", ".join(p.name for p in stale)
        print(f"stale generated files: {names} -- run `make gen`", file=sys.stderr)
        return 1
    if not stale:
        print("generated stat files are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
