"""Render the dbt models' SQL for one just-ingested batch (plan E.1b, ADR-047).

`marts.decisions` and `marts.player_hands` are derived by dbt from `core.*`, a day-partition at
a time, and an upload is not in stats until that runs. The hot path derives the batch the worker
has just inserted with the SAME SQL -- `macros/hand_arrays.sql`, `macros/decision_state.sql`,
`models/marts/player_hands.sql` -- rendered here by Jinja exactly as dbt renders it, with two
substitutions:

  * `dirty_partitions(column)` -- dbt's gate, "which days need rebuilding" -- becomes
    "this tenant, this batch's stamp, this batch's partitions" (`batch_predicate`).
  * `ref('int_board_by_street')` becomes that model's SQL inlined: the just-ingested hands are
    not in the intermediate table yet, so the board features are computed on the spot.

So the derivation is written once, in the dbt macros, and rendered twice. `make gen` writes the
result to `ch/hot_path/<table>.sql`; `make gen-check` fails if it drifts; `ingestion/hot_path.py`
runs it with the three parameters bound.

The batch is identified by its stamp rather than by hand ids because `parsed_at` is stamped once
per ingest batch, reaches every staging view as `src_parsed_at`, and is the one column every call
site of the gate carries in the same form -- while `hand_uid`, a `FixedString(16)` from `core.*`
onwards since plan B.5b, is not a stamp and cannot say which hands a batch was.
The partitions are passed as well, for the pruning the
gate gets: filtering `staging.stg_hands FINAL` by stamp alone costs 1.1 s on a 9M-hand tenant,
with the partition 4 ms (measured on the real database, 2026-09-14).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from jinja2 import Environment, StrictUndefined

PROJECT = Path(__file__).resolve().parent.parent / "dbt" / "poker_dwh"
HEADER = (
    "-- GENERATED by `make gen` from dbt/poker_dwh (the macros and models named below)"
    " -- edit the dbt models, not this file."
)

DERIVATION_MACROS = ("board.sql", "hand_arrays.sql", "decision_state.sql")
"""The macros the fact models are made of. `incremental.sql` (the gate), `provenance.sql`
(`built_by`) and `generate_schema_name.sql` are deliberately NOT loaded: they are the three
things the hot path renders differently, and each is provided below as a Python stub."""

MODELS: dict[str, str] = {
    "decisions": "models/marts/decisions.sql",
    "player_hands": "models/marts/player_hands.sql",
}
BOARD_MODEL = "models/intermediate/int_board_by_street.sql"
STAGING_MODELS = frozenset({"stg_hands", "stg_hand_players", "stg_actions", "stg_pot_winners"})

TENANT_PARAM = "{tenant:UInt32}"
STAMP_PARAM = "{stamp:DateTime64(3, 'UTC')}"
PARTITIONS_PARAM = "{partitions:Array(UInt32)}"
"""The three query parameters `ingestion/hot_path.py` binds. Names, not values: nothing in this
module ever sees a hand."""

HOT_PROVENANCE = "'hot'::LowCardinality(String)"
"""What `{{ built_by() }}` renders to here; dbt renders `'dbt'`. Cast like the macro is, so the
inserted block's type matches the table's."""


def batch_predicate(column: str) -> str:
    """What `dirty_partitions(column)` becomes: the batch, on whichever relation is being read.

    `column` is the played-at column as the macro names it (`played_at_utc`, `h.played_at_utc`,
    `b.played_at_utc`), so its alias prefix is the relation's -- every relation the gate is
    applied to carries `user_id` and `src_parsed_at` under the same alias.
    """
    alias = column[: column.rindex(".") + 1] if "." in column else ""
    return (
        f"toYYYYMMDD({column}) in {PARTITIONS_PARAM}"
        f" and {alias}user_id = {TENANT_PARAM}"
        f" and {alias}src_parsed_at = {STAMP_PARAM}"
    )


def _macros() -> str:
    return "\n".join((PROJECT / "macros" / name).read_text() for name in DERIVATION_MACROS)


def _render(model_path: str) -> str:
    """One model's SELECT, exactly as dbt would render it but for the three stubs."""
    env = Environment(undefined=StrictUndefined, autoescape=False)
    env.globals.update(
        ref=_ref,
        source=lambda schema, name: f"{schema}.{name}",
        config=lambda **_: "",
        dirty_partitions=batch_predicate,
        built_by=lambda: HOT_PROVENANCE,
    )
    template = env.from_string(_macros() + "\n" + (PROJECT / model_path).read_text())
    return template.render().strip()


def _ref(name: str) -> str:
    """The `ref()` of dbt: a staging view by name, the board model inlined, else refused."""
    if name in STAGING_MODELS:
        return f"staging.{name}"
    if name == "int_board_by_street":
        return "(\n" + _render(BOARD_MODEL) + "\n)"
    raise ValueError(f"the hot path cannot ref({name!r}): only staging views and the board model")


def render_hot_path(table: str) -> str:
    """`ch/hot_path/<table>.sql`: INSERT the batch's rows, skipping hands already present.

    The anti-join is what makes the insert idempotent: a Kafka redelivery re-runs the whole
    ingest for the same file, and without it the batch would land twice in a plain MergeTree
    and be counted twice by the rollup's materialized view -- which never forgets an insert.
    Scoped to the batch's own partitions and tenant, so it reads a few day-partitions of
    `hand_uid`, not the table.
    """
    if table not in MODELS:
        raise ValueError(f"no hot path for {table!r}; one of {sorted(MODELS)}")
    return (
        f"{HEADER}\n"
        f"-- The worker's derivation of one batch into marts.{table} (plan E.1b, ADR-047):\n"
        f"-- {MODELS[table]} rendered with the batch predicate in place of dbt's partition gate,\n"
        "-- `int_board_by_street` inlined, and `built_by = 'hot'` so that dbt's gate knows the\n"
        "-- partition is not its own work yet. Three parameters: tenant, stamp, partitions.\n"
        f"INSERT INTO marts.{table}\n"
        "SELECT * FROM (\n"
        f"{_render(MODELS[table])}\n"
        ") AS fresh\n"
        "WHERE fresh.hand_uid NOT IN (\n"
        f"    SELECT hand_uid FROM marts.{table}\n"
        f"    WHERE user_id = {TENANT_PARAM} AND toYYYYMMDD(played_at_utc) IN {PARTITIONS_PARAM}\n"
        ")\n"
    )


def parameters(tenant_id: int, stamp: Any, partitions: list[int]) -> dict[str, Any]:
    """The bound values, named as the rendered SQL expects them."""
    return {"tenant": tenant_id, "stamp": stamp, "partitions": partitions}
