"""The rollup's SQL vocabulary, shared by everything that emits or reads it (ADR-021, ADR-044).

`marts.stats_daily` has two producers -- the dbt model and a ClickHouse materialized view -- and
ADR-003 allows that only on the condition that they express the same logic. The condition is met
structurally rather than by review: `select_body()` below is the single renderer, and both the
dbt model (`scripts/gen_stats.py`) and the view DDL (`render_mv_views()`) are that body with a
different wrapper around it. `scripts/mv_sync.py` uses it a third time for the boundary backfill
and a fourth for `--verify`, and `tests/integration/test_mv_reconciliation.py` proves they agree
in fact.

Nothing here reaches a user's input: values are inlined as literals (`Literals`), which is safe
only because every one of them comes from the registry in this repository.
"""

from __future__ import annotations

from stats.compiler import Compiler, Literals, quote
from stats.definitions import Stat, Table
from stats.registry import Registry

ROLLUP = "stats_daily"
HEADER = "-- GENERATED by `make gen` from stats/registry -- edit the registry, not this file."

KEYS = (
    ("user_id", "user_id", "UInt32"),
    ("dataset", "dataset", "LowCardinality(String)"),
    ("player_key_norm", "player_key", "String"),
    ("played_date", "day", "Date"),
    ("site", "site", "LowCardinality(String)"),
    ("stake_level", "stake_level", "LowCardinality(String)"),
    ("game_type", "game_type", "LowCardinality(String)"),
    ("table_format", "table_format", "LowCardinality(String)"),
    ("position", "position", "LowCardinality(String)"),
    ("is_hero", "is_hero", "UInt8"),
    ("is_anonymized", "is_anonymized", "UInt8"),
)
"""(source column, rollup column, ClickHouse type). Every one of them is in the ORDER BY:
SummingMergeTree merges rows that share the sort key, so a group key outside it would collapse
two groups into one (docs/POKER_AUDIT.md B5). The type is only needed by the MV target table,
which is created by a migration and so cannot infer it from a SELECT; the reconciliation test
asserts the result is structurally identical to the dbt-built rollup, so a drift here is loud."""

ZERO_COUNT = "toUInt64(0)"
ZERO_MONEY = "toDecimal128(0, 4)"
TYPE_OF_ZERO = {ZERO_COUNT: "UInt64", ZERO_MONEY: "Decimal(38, 4)"}
WATERMARK = "src_parsed_at"
WATERMARK_TYPE = "DateTime64(3, 'UTC')"
MV_WATERMARK_TYPE = f"SimpleAggregateFunction(max, {WATERMARK_TYPE})"
"""The MV target's watermark keeps the MAXIMUM across a SummingMergeTree merge; a plain
DateTime64 keeps whichever row came first (ADR-044 measured it, ADR-047 measured it again). The
read path decides which (dataset, day) slices to take from the view by comparing this maximum
with the dbt rollup's, so it must be exact whatever the merge state. The dbt rollup keeps the
plain type: dbt writes each group once per build, so nothing ever merges there."""

DBT_PROVENANCE = "dbt"
"""`built_by` of a fact row dbt derived. The generated rollup aggregates these rows only, so a
row the ingest worker derived (`'hot'`, scripts/hot_path_sql.py) can never advance the anchor
watermark before dbt has derived the same hand itself (ADR-047)."""

MV_MIGRATION = f"0012_mv_{ROLLUP}_v2"
"""`0011` created the first target and is frozen: the runner is append-only, so the type change
needs a new file, and one that drops what 0011 made -- a derived table, rebuilt by
`scripts/mv_sync.py --recreate` from `marts.*` in minutes."""
MV_ALIAS = "fact"
SOURCES: tuple[Table, ...] = ("decisions", "player_hands")
"""The two fact tables the rollup unions, and so the two views. One view per source: a
materialized view triggers on exactly one table."""
MV_TARGET = f"{ROLLUP}_mv"
"""The MV writes HERE, never into `marts.stats_daily` (ADR-044).

`marts.stats_daily` is the incremental chain's anchor: `dirty_partitions()` asks whether
`max(core.hands.parsed_at)` for a day exceeds the `max(src_parsed_at)` already built for it.
`parsed_at` is stamped once per ingest batch and flows straight through to `src_parsed_at`, so
an MV writing its own rows into the anchor makes `built_max` equal `src_max` at the instant the
batch lands -- and the gate is a strict `>`, so the day reads CLEAN for ever and the fact tables
are never built for it. A separate target keeps the anchor exactly as dbt left it, and has the
second virtue that the two producers' rows stay side by side and directly comparable, which is
what the reconciliation test is."""

BOUNDARY = "mv_boundaries"
"""MVs are forward-only: one sees only rows inserted after it exists, and `POPULATE` drops
whatever lands during its run. So the boundary is written FIRST, the view filters
`src_parsed_at >= boundary`, and everything below the boundary is backfilled by an ordinary
INSERT ... SELECT (`scripts/mv_sync.py`) -- the pattern docs/POKER_DATA_MODEL.md §464 already
specifies. It lives in a table rather than in the DDL so the generated file stays byte-stable
for `make gen-check`."""


def rollup_columns(stat: Stat, compiler: Compiler) -> list[tuple[str, str, str]]:
    """(column, expression on the stat's own table, zero for the other table) per stat.

    A ratio stat yields its `_opp` / `_action` pair; a bare count yields one column named
    after the stat (`hands`). Sums are widened to Decimal(38, 4) so both UNION branches agree
    on the type whatever the source column is.
    """
    numerator = compiler.expr(stat.numerator_expr)
    if stat.denominator_expr is None:
        return [(stat.code, numerator, ZERO_COUNT)]
    denominator = compiler.expr(stat.denominator_expr)
    return [
        (f"{stat.code}_opp", denominator, _zero(denominator)),
        (f"{stat.code}_action", numerator, _zero(numerator)),
    ]


def _zero(expression: str) -> str:
    return ZERO_MONEY if expression.startswith("sum(") else ZERO_COUNT


def _widen_sums(expression: str) -> str:
    """`sum(x)` -> `sum(toDecimal128(x, 4))`, so Decimal and Float sources land in one type."""
    if expression.startswith("sum(") and expression.endswith(")"):
        return f"sum(toDecimal128({expression[4:-1]}, 4))"
    return expression


def _group_by() -> str:
    """The rollup's group keys, in ORDER BY order."""
    return ", ".join(target for _, target, _ in KEYS)


def select_body(reg: Registry, table: Table) -> str:
    """The SELECT list both producers share: keys, every cached stat's columns, the watermark.

    **This function is the no-drift guarantee of ADR-003.** The dbt model and the ClickHouse
    materialized view are the same statistics computed by the same engine on the same rows; the
    only honest way to keep them equal is for one renderer to emit both, which is this one. The
    two callers add nothing but the wrapper around it -- dbt's `ref()`/dirty-partition gate, or
    the view's `CREATE ... TO` and boundary predicate.
    """
    lines = [
        f"    {source}{'' if source == target else ' as ' + target}," for source, target, _ in KEYS
    ]
    for stat in reg.stats.values():
        if not stat.cached:
            continue
        own = Compiler(dims=reg.dimensions, table=stat.table, values=Literals())
        for column, expression, zero in rollup_columns(stat, own):
            value = _widen_sums(expression) if stat.table == table else zero
            lines.append(f"    {value} as {column},")
    lines.append(f"    max({WATERMARK}) as {WATERMARK}")
    return "select\n" + "\n".join(lines)


def _branch(reg: Registry, table: Table, ref: str) -> str:
    """One UNION ALL branch of the dbt rollup: the shared body over a dbt `ref`, behind the gate.

    `built_by = 'dbt'` is the second half of ADR-047's race guard: rows the ingest worker
    derived are aggregated by the materialized view, never by this model, so the rollup's
    watermark for a day only ever says what dbt itself has derived.
    """
    return (
        select_body(reg, table)
        + f"\nfrom {{{{ ref('{ref}') }}}}\nwhere {{{{ dirty_partitions('played_at_utc') }}}}"
        + f" and built_by = '{DBT_PROVENANCE}'"
        + f"\ngroup by {_group_by()}"
    )


def rollup_column_types(reg: Registry) -> list[tuple[str, str]]:
    """(column, ClickHouse type) for every column of the rollup, in SELECT order.

    The type of a stat column is the type of its zero: `_zero()` already decides Decimal vs
    UInt64 from the expression, and both UNION branches must agree on it, so the zero is the
    one place that knowledge lives.
    """
    columns = [(target, ch_type) for _, target, ch_type in KEYS]
    for stat in reg.stats.values():
        if not stat.cached:
            continue
        own = Compiler(dims=reg.dimensions, table=stat.table, values=Literals())
        for column, _, zero in rollup_columns(stat, own):
            columns.append((column, TYPE_OF_ZERO[zero]))
    columns.append((WATERMARK, WATERMARK_TYPE))
    return columns


def mv_target_column_types(reg: Registry) -> list[tuple[str, str]]:
    """The MV target's columns: the rollup's, with the watermark as an aggregate maximum."""
    return [
        (name, MV_WATERMARK_TYPE if name == WATERMARK else ch_type)
        for name, ch_type in rollup_column_types(reg)
    ]


def value_columns(reg: Registry) -> list[str]:
    """Every rollup column that carries a number: what a reconciliation must compare."""
    keys = {target for _, target, _ in KEYS}
    return [n for n, _ in rollup_column_types(reg) if n not in keys and n != WATERMARK]


def group_sums_sql(marts: str, table: str, reg: Registry, where: str = "1") -> str:
    """A rollup table's meaning: one row per group key, every counter summed.

    Sums rather than rows because both rollups are `SummingMergeTree` and can hold a different
    NUMBER of rows while meaning the same thing (one part per dbt build, one per insert block
    through the view); summing per group compares what they mean whatever the merge state.
    `where` narrows both sides the same way -- a day, a tenant -- and is never caller text.
    """
    keys = ", ".join(target for _, target, _ in KEYS)
    sums = ", ".join(f"sum({c}) as {c}" for c in value_columns(reg))
    return f"select {keys}, {sums} from {marts}.{table} where {where} group by {_group_by()}"


def disagreements_sql(marts: str, left: str, right: str, reg: Registry, where: str = "1") -> str:
    """How many group-rows of `left` `right` does not match exactly, within `where`.

    On the real corpus the two rollups hold ~2.5M group-rows of 113 counters each, and an
    EXCEPT over the whole of both needs more than the 2.33 GiB query ceiling; `scripts/mv_sync.py
    --verify` therefore runs this once per day-partition, which is also how it names the days
    that differ.
    """
    return (
        f"select count() from ( {group_sums_sql(marts, left, reg, where)}"
        f" except {group_sums_sql(marts, right, reg, where)} )"
    )


def render_mv_migration(reg: Registry) -> str:
    """`ch/migrations/0012_mv_stats_daily_v2.sql`: the MV target, recreated with an exact watermark.

    Only the table -- the views themselves are in `ch/views/` because they depend on
    `marts.decisions`, which dbt owns and which does not exist when migrations run
    (`api/provision.py` migrates, THEN builds the empty marts). A migration that referenced it
    would fail on every fresh environment. `_meta.mv_boundaries` is 0011's and stays.

    Drops before it creates, views first: the target is derived data (a materialized view's
    output plus a backfill from `marts.*`), rebuilt by `scripts/mv_sync.py --recreate`, and a
    view whose target is gone would fail every insert into its source. `api/provision.py` runs
    `--create` after every migration, so a fresh or a migrated environment ends up with the
    views in place.
    """
    columns = ",\n".join(f"    {name} {ch_type}" for name, ch_type in mv_target_column_types(reg))
    drops = "".join(f"DROP VIEW IF EXISTS marts.{MV_TARGET}_{source};\n" for source in SOURCES)
    return (
        f"{HEADER}\n"
        "-- The materialized-view half of the rollup (ADR-003, ADR-025, ADR-044, ADR-047): a\n"
        "-- target table shaped exactly like `marts.stats_daily`, except that its watermark is\n"
        "-- an aggregate MAXIMUM -- a plain DateTime64 keeps whichever row a SummingMergeTree\n"
        "-- merge saw first, and the read path compares this watermark with the dbt rollup's\n"
        "-- to decide which (dataset, day) slices the view serves. Supersedes 0011's target.\n"
        "--\n"
        "-- The MV does NOT write into `marts.stats_daily`, and that is the whole point: that\n"
        "-- table is the incremental chain's anchor, and a second writer in it makes the\n"
        f"-- dirty-partition gate compare a value against itself. See {MV_TARGET} in\n"
        "-- scripts/rollup_sql.py for the failure in full.\n\n"
        f"{drops}"
        f"DROP TABLE IF EXISTS marts.{MV_TARGET};\n\n"
        f"CREATE TABLE IF NOT EXISTS marts.{MV_TARGET} (\n"
        f"{columns}\n"
        ") ENGINE = SummingMergeTree()\n"
        "PARTITION BY toYYYYMMDD(day)\n"
        f"ORDER BY ({_group_by()});\n"
    )


def render_mv_views(reg: Registry) -> str:
    """`ch/views/stats_daily_mv.sql`: one MV per source table, re-applied whenever it changes.

    Dropped and recreated rather than `IF NOT EXISTS`: a view is pure derived DDL and dropping
    one never touches a row of its target, so re-applying is free -- and it has to be free,
    because a registry change must reach the database or the two producers drift, which is the
    one thing this step exists to prevent.
    """
    boundary = f"(select boundary_at from _meta.{BOUNDARY} final where view = "
    views = []
    for table in SOURCES:
        name = f"{MV_TARGET}_{table}"
        views.append(
            f"DROP VIEW IF EXISTS marts.{name};\n\n"
            f"CREATE MATERIALIZED VIEW marts.{name} TO marts.{MV_TARGET} AS\n"
            + select_body(reg, table)
            + f"\nfrom marts.{table} as {MV_ALIAS}\n"
            # Qualified: the SELECT aliases `max(src_parsed_at) as src_parsed_at`, and an
            # unqualified mention in WHERE resolves to that alias, which ClickHouse rejects as
            # an aggregate in WHERE. The alias names the row's own column unambiguously.
            + f"where {MV_ALIAS}.{WATERMARK} >= {boundary}{quote(name)})\n"
            + f"group by {_group_by()};\n"
        )
    return (
        f"{HEADER}\n"
        "-- Applied by `scripts/mv_sync.py`, NOT by the migration runner: the runner is\n"
        "-- append-only and skips a version it has already seen, so a regenerated file would\n"
        "-- never reach the database and the view would silently keep the old registry's logic.\n"
        "--\n"
        "-- The SELECT below is emitted by the SAME `select_body()` that writes the dbt model\n"
        "-- (dbt/poker_dwh/models/marts/stats_daily.sql). They cannot disagree by construction.\n"
        "-- `tests/integration/test_mv_reconciliation.py` proves they do not disagree in fact.\n"
        "--\n"
        "-- A materialized view sees only rows inserted AFTER it exists, so each one is fenced\n"
        "-- by its boundary row and everything below it is backfilled by an ordinary INSERT.\n\n"
        + "\n".join(views)
    )
