"""Markdown sections built from the preflop/flop nodes alone (no board texture).

Section A is the plan: one ranking of every spot by how often it happens, flop-reaching and
preflop-only together, because that is the order the spots are actually met at the table.
Whether a spot has a postflop tree changes *what* the study session contains, not when it is
worth doing -- so it is a column, not a separate list.
"""

from __future__ import annotations

from scripts.spot_nodes import MIN_HANDS, WALK, Spot

TOP_MD_ROWS = 60  # rows shown in the markdown; the CSV always carries every node
TOP_FLOP_NODES = 20  # how many preflop nodes get their flop continuation broken out
TOP_PATTERNS = 30
MIN_LINE_PCT = 1.0  # flop lines rarer than this are folded into an "other" row
MOSTLY = 99.0  # flop% at or above which a node is treated as always reaching a flop

FlopLines = dict[str, list[tuple[str, int]]]


def table(headers: list[str], rows: list[list[str]]) -> list[str]:
    """One markdown table as a list of lines."""
    return [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
        *["| " + " | ".join(r) + " |" for r in rows],
    ]


def work_kind(s: Spot) -> str:
    """What a study session on this spot actually consists of."""
    if s.flop_pct >= MOSTLY:
        return "postflop"
    if s.flop_pct <= 100 - MOSTLY:
        return "preflop only"
    return "mixed"


def header(total: int, flops: int, walk: int) -> list[str]:
    """Report title and how to read it."""
    return [
        "# Spot frequency — pool census and study order",
        "",
        f"**{total:,} hands** · GGPoker Rush & Cash · 6-max NL Hold'em · NL2-NL25 pooled · "
        "generated by `scripts/spot_frequency.py`",
        "",
        "A *spot* is the preflop action sequence with folds compressed out, so `BU open, BB "
        "call` means everyone else folded.",
        "",
        f"Section A is the plan: every spot in one list, most frequent first, whether or not it "
        f"reaches a flop. {100 * flops / total:.1f}% of hands see a flop ({flops:,}); the rest "
        "end preflop and are range work rather than board work. The `work` column says which "
        f"kind each spot is. Walks ({walk:,}, {100 * walk / total:.1f}% of hands) are excluded "
        "from the ranking — there is no decision in them — but they stay in the denominator.",
        "",
    ]


def section_plan(spots: list[Spot], decision_hands: int) -> list[str]:
    """The plan: every spot ranked by frequency, flop-reaching and preflop-only together."""
    ranked = [s for s in spots if s.spot != WALK]
    out = [
        "## A. The plan — every spot by frequency",
        "",
        f"Ranked by how often the spot happens at all. `cum %` runs over the {decision_hands:,} "
        "hands that contain a decision (all hands except walks), so it reads as: study down to "
        "this row and you have covered that share of the hands you actually play.",
        "",
        "`work` is what the session contains — `preflop only` spots have no board to reason "
        "about and are pure range work; `postflop` spots carry a flop tree (section C pairs "
        "them with board texture).",
        "",
    ]
    rows, cum = [], 0.0
    for i, s in enumerate(ranked[:TOP_MD_ROWS], 1):
        cum += 100 * s.hands / decision_hands
        rows.append(
            [
                str(i),
                f"`{s.spot}`",
                s.level,
                work_kind(s),
                f"{s.hands:,}",
                f"{100 * s.hands / decision_hands:.2f}%",
                f"{cum:.1f}%",
                f"{s.flop_hands:,}",
                f"{s.avg_pot_bb:.1f}",
            ]
        )
    out += table(
        ["#", "spot", "pot", "work", "hands", "% hands", "cum %", "flops", "avg pot bb"], rows
    )
    return [*out, ""]


def section_patterns(spots: list[Spot], total: int) -> list[str]:
    """Nodes with positions stripped: the shape of the game, independent of seat."""
    agg: dict[str, list[int]] = {}
    for s in spots:
        cur = agg.setdefault(s.pattern, [0, 0])
        cur[0] += s.hands
        cur[1] += s.flop_hands
    ranked = sorted(agg.items(), key=lambda kv: -kv[1][0])
    out = [
        "## D. Action patterns — positions stripped",
        "",
        "The same node with seats removed, so `BU open, BB call` and `CO open, BB call` collapse "
        "into `open, call`. This is the level to pick a *topic* at; section A picks the seat.",
        "",
    ]
    rows = [
        [str(i), f"`{pat}`", f"{h:,}", f"{100 * h / total:.2f}%", f"{f:,}"]
        for i, (pat, (h, f)) in enumerate(ranked[:TOP_PATTERNS], 1)
    ]
    out += table(["#", "pattern", "hands", "% hands", "flops"], rows)
    return [*out, ""]


def _flop_rows(spot: Spot, node_lines: list[tuple[str, int]]) -> list[list[str]]:
    """Flop lines for one node, with everything under MIN_LINE_PCT collapsed into `other`."""
    rows, rest = [], 0
    for line, n in node_lines:
        pct = 100 * n / spot.flop_hands
        if pct >= MIN_LINE_PCT:
            rows.append([f"`{line}`", f"{n:,}", f"{pct:.1f}%"])
        else:
            rest += n
    if rest:
        rows.append(["_other lines <1% each_", f"{rest:,}", f"{100 * rest / spot.flop_hands:.1f}%"])
    return rows


def section_flop(spots: list[Spot], lines: FlopLines) -> list[str]:
    """Flop continuation under each of the top preflop nodes."""
    out = [
        "## E. Flop continuation for the top spots",
        "",
        "What the pool actually does once the flop comes down, per preflop node. Percentages are "
        "within the node, so each block sums to 100%.",
        "",
    ]
    for s in [x for x in spots if x.is_playable][:TOP_FLOP_NODES]:
        out += [f"### `{s.spot}` — {s.flop_hands:,} flops ({s.avg_pot_bb:.1f} bb avg pot)", ""]
        out += table(["flop line", "hands", "% of node"], _flop_rows(s, lines.get(s.spot, [])))
        out += [""]
    return out


def caveats() -> list[str]:
    """What the numbers do and do not support."""
    return [
        "## Method & caveats",
        "",
        f"- Nodes below {MIN_HANDS} hands are dropped entirely, from both the report and the CSV.",
        "- Hero's own seats are included (0.22% of hands) — this is a pool census, not a leak "
        "report. `pool_report.py` is the hero-excluded one.",
        "- All-in raises are labelled by their raise ordinal, not marked separately (1.3% of "
        "preflop raises).",
        "- A node ending in a raise can still show a handful of flops (~0.08% of `open, 3bet`). "
        "That is correct: a player who was already all-in and called is owed a runout even when "
        "a later raise drives the caller out, so the board is dealt with no call in the node.",
        f"- `{WALK}` is excluded from the section A ranking (no decision in it) but stays in the "
        "all-hands denominator.",
        "- Board texture uses the ace as high **or** low, so A-2-3 is connected. "
        "`int_board_texture.sql` in the dbt chain is ace-high only and disagrees on those "
        "boards; this file's definition is the correct one.",
        "- Rush & Cash dissolves the table every hand, so there is no table or session context; "
        "every hand is independent and position is re-drawn each time.",
        "- `avg pot bb` is the *final* pot including all streets, so it reads high on nodes that "
        "go deep. It is a money-weight hint, not a preflop pot size.",
        "",
    ]
